### ISSUE TITLE
Inline generating in the specific class

### ISSUE THREAD

**Issue by pavel-trafimuk** [krzysztofzablocki/Sourcery#1021]
Hello all.
I had a huge codebase, where Sourcery parsing is too slow, so I used one swift file as a `source` for generation (with enum with frameworks list under the hood). On the base of this enum I want to generate an assembly for each framework. 
Some fully generated files works great with `per-file annotation`, 
but I detected that I can't say _"put this piece of the code in this 'inline' block for this file"_. It doesn't work. 
As I understand - Sourcery looks for 'inline' in 'Source' files, which are only one (for performance reasons)
So suggestion, if I use 'inline' annotation inside 'per-file' annotation - can Sourcery looks for inline in this file only (or in this file at first for backward compatibility)

**Comment by krzysztofzablocki** [comment]
Your understanding is correct, Inline annotations only work in parsed Sources, otherwise we don't know anything about the files so we wouldn't know where to replace things.

what size of codebase do you have? and how slow it is? 
Sourcery runs in projects like Bumble / Airbnb and they have milions of line of Swift, it's heavily cached too
