### ISSUE TITLE
Better support for escaping function types

### ISSUE THREAD

**Issue by marinbenc** [krzysztofzablocki/Sourcery#103]
In some use-cases, it would be useful to get a typeName of a function that includes the `@escaping` attribute, and one that doesn't include it.

For instance, when assigning an escaping function parameter to a variable outside of that function. The parameter `typeName` has to be `@escaping (String)-> Void`, but in variables and tuples, functions are implicitly escaping, and thus don't require the `@escaping` annotation.

```
var onComplete: (String)-> Void

func someFunc(onComplete: @escaping (String)-> Void) {
  self.onComplete = onComplete
}
```

The `typeName` for these two is different, in the function parameter it's `@escaping (String)-> Void`, and in the variable it's just `(String)-> Void`.

It would be nice to expose `nonEscapingTypeName` in `Parameter`.

Another way to handle this would be by adding a custom `replaceSubrange` filter for Stencil strings, although that would be a separate issue.

**Comment by ilyapuchka** [comment]
I also think we should have that. But I wonder if we can just add trimming of `@escaping` attribute in `unwrappedTypeName`? Also we may add a `unwrapped` filter for `TypeName`.

P.S. We also will need to add support for `@autoclosure` attribute and maybe `@discardableResult` attribute of a method. I would add `attributes` collection maybe for that. Also supporting `@available` seems like valuable improvement.

**Comment by krzysztofzablocki** [comment]
So does the following cover it?:

- make `unwrappedTypeName` remove all `@autoclosure, @discardableResult, @available` etc
- add `attributes` into `typeName` that would contain all those @ keywords

I'd wait with `unwrapped` filter because I don't think its going to be that useful until we have map function, since we can't do for `types.typeName|unwrapped` now anyway

**Comment by ilyapuchka** [comment]
Pretty much, except `@discardableResult` is only for methods. SourceKit looks like trims it automatically, so we just need to put it in attributes. Parsing `@available` will be cumbersome as SourceKit only returns attribute identifier, but we have to parse its content manually...

Why can't we use filter like that? Wouldn't it work if we return just a `String` in a filter method?

**Comment by krzysztofzablocki** [comment]
@ilyapuchka the reason adding `unwrapped` now might be an overkill is due to the fact that stencil doesn't generate an array when doing `{% for info in type.Complex.allMethods.returnTypeName %}{{info}}{% endfor %}`, which is a little surprising because from what I recall `valueForKeyPath` would, we can wait for map node and then `unwrapped` might be unnecesary
