### ISSUE TITLE
Improve default value type inferrence

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#111]
If I have a type like this

```swift
struct B {
 let d = true
}
```

there is no way in the stencils to know that `d` exists (at least, I haven't found it).

Now, of course it is not possible to know that `d` is a `Bool`, since Sourcery currently doesn't have information about things that it doesn't scan. I think that `d` should be listed though. Maybe with an empty type?
Otherwise it is impossible to add errors in the code.

Use case: I have this stencil for auto equatable, and if developers forget to use the proper syntax, there is not easy way (besides review the generated code) to check that all the variables have been correctly handled. My idea is to add either a comment, or something that make the code fail to compile. It is a safer apporach

**Comment by ilyapuchka** [comment]
@bolismauro thanks for spotting that.

I think we might skip it because SourceKitten does not provide information about inferred type (https://github.com/jpsim/SourceKitten/issues/240). If that's the case looks like it's still possible with some additional arguments passed to SourceKitten so maybe we can try to do that.

Regarding errors I guess Sourcery should only warn in the console in case it skips some declarations, but not fail the build. I feel like it's work for linters, not code generators. What do you think @krzysztofzablocki

**Comment by krzysztofzablocki** [comment]
I was going to link to same sourcekitten issue ;) 
We already list variables variables of unkown types, this issue is only related to automatic type inferrence, we can investigate using that sourcekitten arguments to lookup types that are part of foundation. 

Logging is one thing, we should do that for sure, but I also think that @bolismauro is right that this can be serious error, so adding a variable without type might be better here. In many scenarios it would lead to working template or just force developers to adjust their definition

**Comment by ilyapuchka** [comment]
Agree. I'll investigate how we can handle that.

**Comment by bolismauro** [comment]
Just to clarify. I don't think Sourcery should fail.
I was thinking to manage it in my stencil (e.g., by adding a comment or something that doesn't even make the code compile)

Thanks!

**Comment by krzysztofzablocki** [comment]
yeah but one of the driving goals of Sourcery is to prevent bugs so we should list the variable, even without type, that way some templates might fail and users will be required to deal with it, thus preventing bugs :) many templates don't depend on variable type so it would work fine.

**Comment by bolismauro** [comment]
absolutely :)
