### ISSUE TITLE
Version 2.0.0 was removed

### ISSUE THREAD

**Issue by iMichka** [krzysztofzablocki/Sourcery#1139]
Hello.

Homebrew maintainer here. We shipped version 2.0.0 around 2 weeks ago. That version got removed.
We are wondering what happened. Do you plan to ship a new release? Ideally 2.0.1 as 2.0.0 has already been used.

Thanks

**Comment by krzysztofzablocki** [comment]
@iMichka made new one https://github.com/Homebrew/homebrew-core/pull/122419

**Comment by chenrui333** [comment]
Thanks @krzysztofzablocki for the new release, don't remove the existing one in the future. Thanks! 🙏

**Comment by tarbaiev-smg** [comment]
I'd like to note that the Sourcery swift package does not support semver (because of a dependency to the SwiftSyntax branch), hence the removed 2.0.0 cannot be simply succeeded by 2.0.1 in SPM breaking previously working setups.
My mistake was adopting 2.0.0 too soon 😞

**Comment by tarbaiev-smg** [comment]
@iMichka The problem is that SPM considers Sourcery package unstable as it's referencing SwiftSyntax as a branch. The branches are also considered to be unstable (which they are essentially), only tags or fixed revisions are considered stable.
This was already mentioned in https://github.com/krzysztofzablocki/Sourcery/issues/1102.
