### ISSUE TITLE
[Question] Using Sourcery In Swift Package Executable

### ISSUE THREAD

**Issue by vykut** [krzysztofzablocki/Sourcery#1167]
Hello,

Is it possible to use Sourcery in a Swift Package Executable?

I'm trying to create a script using Swift Argument Parser that will generate code using `Sourcery`, based on a template, and then run `SwiftFormat` on the generated code. 

I can see the code generation is done by the `Sourcery` class, but I don't have access to it in my package (I need to import SourceryLib which is not available externally). 

Is there something I'm missing? Is it just not possible what I want to achieve?

Thanks

**Comment by krzysztofzablocki** [comment]
`SourceryFramework` is probably what you want to use?

**Comment by vykut** [comment]
Hmm, maybe. But looking at it, I'm not quite sure how I should use it, because I want to parse & generate the code for the whole project in one go, similarly to how it works when running the `sourcery` command in Terminal.

I was looking at the `Generator.generate` method, which accepts a `Template`, but my template is a `.swifttemplate` file which, its Swift counterpart, `SwiftTemplate`, does not conform to `Template`.

**Comment by krzysztofzablocki** [comment]
@vykut it does conform, but it's inside the SwiftTemplate under Sourcery/Generating/Templates/SwiftTemplate:

```swift
import Foundation
import SourceryFramework
import SourceryRuntime
import SourcerySwift

extension SwiftTemplate: Template {

    public func render(_ context: TemplateContext) throws -> String {
        return try self.render(context as Any)
    }

}

```

**Comment by art-divin** [comment]
Hello @vykut ,

well respected @krzysztofzablocki has merged my [MR](https://github.com/krzysztofzablocki/Sourcery/pull/1170), which enabled exactly this - now it is possible to `import SourceryLib` and use `Configuration` and `Sourcery` in SPM executable targets to manage parsing process and results however you'd like.

Feel free to ask any questions 🙏 

P.S. I have tried a lot of different variants, but the only way I could achieve manual control over parsing via Sourcery class was doing exactly this change. `SouceryFramework` & co did not expose enough classes, because they internally depend on `SouceryLib` but did not re-export or exposed that.
