### ISSUE TITLE
Add LinuxMain generation template

### ISSUE THREAD

**Issue by swizzlr** [krzysztofzablocki/Sourcery#118]
Automatically finding all methods of subclasses of XCTestCase that begin with `test` and generating a `LinuxMain.swift` file will reduce the possibility of error in many cases. This would be super useful as an example for Sourcery and also (IMO) a "killer app". I was wondering if anyone has already done this – otherwise, I may have one that I could contribute (it's very rough and fragile right now).

**Comment by krzysztofzablocki** [comment]
Can you write down more details? not sure I follow

**Comment by swizzlr** [comment]
Sorry – jotting it down half asleep wasn't very useful. I'll edit the comment.

**Comment by vknabel** [comment]
@krzysztofzablocki @swizzlr wants to generate the `LinuxMain.swift` for SwiftPM projects (which would be AWESOME). As Swift on Linux cannot profit from ObjC's runtime, you have to declare all `XCTestCaseEntry`s manually. Usually one solves this per Test Target as follows:

[apple/swift-package-manager/Tests/LinuxMain.swift](https://github.com/apple/swift-package-manager/blob/master/Tests/LinuxMain.swift)
[apple/swift-package-manager/Tests/BasicTests/XCTestManifests.swift](https://github.com/apple/swift-package-manager/blob/master/Tests/BasicTests/XCTestManifests.swift)

Maintaining this is very error prone, as you usually develop on macOS, where tests „just work“ because of the ObjC Runtime, but tests fail when running on Linux (e.g. on your CI). 
https://github.com/apple/swift-package-manager/commit/73a0f511b6ca10c1d9d1e9239dbfdb031560e8fa

**Comment by krzysztofzablocki** [comment]
Generating that should be very straightforward, but I wonder if we wouldn't need to first make Sourcery work on Linux? 

I know sourcekitten supports linux and other dependencies that I've in this project should also work (maybe without the watcher).

**Comment by swizzlr** [comment]
@krzysztofzablocki not necessarily – we can commit the outputs and push it onto Linux.

**Comment by vknabel** [comment]
@krzysztofzablocki Currently you can at least test your code for Linux if you have previously generated it on macOS. This seems weird, but it's nice for CIs.

SwiftTryCatch doesn't support Linux. KZFileWatchers may actually support it as it only depends on Foundation.
The other deps should definitely support Linux.

**Comment by krzysztofzablocki** [comment]
We no longer actually use KZFileWatchers because I moved into FileSystemEvents because they offer us more granular info on folders wheres my pod focuses on single files (need to remove file watcher pod here). SwiftTryCatch is only a try catch wrapper function in objc so as long as that works on Linux we can make that work

**Comment by ilyapuchka** [comment]
On weekend I can try to write a template for that for Dip which also Linux compatible. Wonder if we are not missing anything for that.

**Comment by swizzlr** [comment]
Amazing! 🍾
