### ISSUE TITLE
Not able to build GraphQL target - Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by 08Sanket** [krzysztofzablocki/Sourcery#1181]
For existing project, not able to build target of GraphQL.
Already tried reinstalling homebrew, sourcery, cleared derived data.
Same is working on others system.
Please help with this.

**Comment by art-divin** [comment]
👋 Hello @08Sanket ,

thank you very much for your report!

Could you try sharing the contents of the build phase "Run Script"?

Seems like the arguments you are passing to `Sourcery` are not wrapped inside of `""` and because of this, due to the fact that the working directory contains spaces - `App-wireless/CoxAccount App-wireless/CoxAccount/Networking/GraphQL/Generated App-wireless/CoxAccount` - bash cannot interpret such arguments correctly.

**Comment by 08Sanket** [comment]
Hey,

PATH="$PATH:/opt/homebrew/bin"

sourcery --templates $BUILD_DIR/../../SourcePackages/checkouts/cn-swift-graphql-service/Templates/GraphQLExtensions.stencil --sources $SRCROOT/$PROJECT --sources $BUILD_ROOT/../../SourcePackages/checkouts/cn-swift-graphql-service/Sources/GraphQLServiceCore --sources $BUILD_ROOT/../../SourcePackages/checkouts/coxconnect-ios-models-error/Sources/ErrorModels --sources $BUILD_ROOT/../../SourcePackages/checkouts/coxconnect-ios-models-profile/Sources/ResiProfileModels --sources $BUILD_ROOT/../../SourcePackages/checkouts/coxconnect-ios-models-profile/Sources/CommonProfileModels --output $SRCROOT/$PROJECT/Networking/GraphQL/Generated --args moduleSourcePath=$SRCROOT/$PROJECT --args imports=ErrorModels --args imports=ResiProfileModels --args imports=CommonProfileModels
