### ISSUE TITLE
How to Determine Whether a Function or Property in Swift is Marked as Dynamic

### ISSUE THREAD

**Issue by Tory-Xu** [krzysztofzablocki/Sourcery#1243]
``` swift
dynamic static func dynamicStaticMethod1() {}
```
How can the presence of the "dynamic" attribute be detected when added before a function? The attributes cannot be retrieved using the standard method. What steps should be taken to determine if a function is marked as "dynamic"?

attributes is empty：
```
Method: name = dynamicStaticMethod1(), selectorName = dynamicStaticMethod1, parameters = [], returnTypeName = Void, isAsync = false, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = true, isClass = false, isFailableInitializer = false, annotations = [:], documentation = [], definedInTypeName = Optional(TestClass), attributes = [:], modifiers = [<SourceryRuntime.Modifier: 0x6000_0261_D410>, <SourceryRuntime.Modifier: 0x6000_0261_D440>]
```

**Comment by art-divin** [comment]
👋🏻  Hello @Tory-Xu ,

Thank you very much for the issue 👍🏻 

I have checked and it seems like `Method.attributes`, which is a map of type `[String: [Attribute]]`, does not contain such `Attribute` of type `dynamic` due to simple lack of such attribute in the `Attribute.Identifier` enum. 

So, this is just not supported and needs to be implemented. 

Good news: I have time to do it before the next 2.1.3 release!

**Comment by art-divin** [comment]
👋🏻  Hello

For correctness, in my previous analysis I was misunderstanding the difference between attribute and modifier for methods and variables. In fact, `dynamic` is a _modifier_ and not an attribute.

PR is being verified by the CI at the moment, soon to be merged.

**Comment by Tory-Xu** [comment]
Thanks a lot!
