### ISSUE TITLE
The platform of the target `MyApp` (iOS 16.0) is not compatible with `Sourcery (2.1.4)`, which does not support `iOS`

### ISSUE THREAD

**Issue by Shiaulis** [krzysztofzablocki/Sourcery#1260]
Hey folks 👋🏾
After recent Sourcey update my `pod update` command stopped working because of error:
```
[!] The platform of the target `MyApp` (iOS 16.0) is not compatible with `Sourcery (2.1.4)`, which does not support `iOS`.
```
My platform in Podfile:
```
platform :ios, "16.0"
```
- We added sourcery to our pods many years ago, it worked well all the time. 
- Didn't change anything recently within Podfile itself. 
- Didn't find any limitations regarding platform connected to recent update

Any advices what can help us?

**Comment by art-divin** [comment]
Hello @Shiaulis ,

thank you for reporting the issue!

The thing is, there is in fact a difference between the old `podspec` and the new `podspec`. The platform was not specified before 2.1.4 at all, so all platforms were implied to be supported. See the [podspec for 2.0.1](https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/2/Sourcery/2.0.1/Sourcery.podspec.json) and [podspec for 2.1.4](https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/2/Sourcery/2.1.4/Sourcery.podspec.json) for comparison.

This needs a new release to CocoaPods with 2.1.5, I’ll try to take care of it as soon as today 🤝🏻

I wonder, are you shipping Sourcery along with the product? Because we do not have [The Privacy Manifest](https://github.com/krzysztofzablocki/Sourcery/issues/1235) yet.

**Comment by Shiaulis** [comment]
Yes, for now we are shipping sourcery within the product. Regarding upcoming changes from Apple we are keeping eye on it and I assume we will change the way we are using dev tools in our dependencies in near future, so thanks for pointing that out 🙏🏾
And surely thanks for quick reaction and explanation 🙇🏾‍♂️

**Comment by art-divin** [comment]
Running release CI pipelines, soon 2.1.5 will be available with the fix. ⏲️

**Comment by arbyruns** [comment]
Will this also be included in the pod spec?

**Comment by art-divin** [comment]
@arbyruns 

> Will this also be included in the pod spec?

Indeed, 2.1.5 was just pushed to cocoapods. Brew is not yet pushed though, takes time. 🕐

**Comment by art-divin** [comment]
👋🏻  Hey,

I think that 2.1.5 only supports watchOS 🙈 

I'll need to re-release again ⏲️

**Comment by art-divin** [comment]
2.1.6 has just been released to `cocoapods`; homebrew - trying to make it work ⏲️ 

https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/2/Sourcery/2.1.6/Sourcery.podspec.json confirms that all platforms are supported as prior to 2.1.4.

**Comment by Shiaulis** [comment]
Not sure if this is connected, but now I have another type of issue:
```
[13:19:26]: ▸ Pod installation complete! There are 64 dependencies from the Podfile and 77 total pods installed.
[13:19:26]: ---------------------------------------------------------------------------
[13:19:26]: --- Step: ./Pods/Sourcery/bin/sourcery --verbose --config .sourcery.yml ---
[13:19:26]: ---------------------------------------------------------------------------
[13:19:26]: $ ./Pods/Sourcery/bin/sourcery --verbose --config .sourcery.yml
+--------------------------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios update_dependencies |
+------------------+-------------------------+
[13:19:26]: No such file or directory - ./Pods/Sourcery/bin/sourcery

**Comment by Shiaulis** [comment]
we are using simply `pod "Sourcery"`, not CLI version and without specifying particular version

**Comment by Shiaulis** [comment]
I assume confusion is coming from path. It is expected `./Pods/Sourcery/bin/sourcery` but what i see in my pods is this:
![image](https://github.com/krzysztofzablocki/Sourcery/assets/13601748/bf57a607-3ceb-4ea0-8259-721aa97f5561)

**Comment by art-divin** [comment]
Yes, confirm, for now you can revert to `2.0.1` version; I am fixing 2.1.7 one at the moment.

**Comment by art-divin** [comment]
Found the reason - and it is quite sophisticated! 

1. Previously, 2.0.1 version was compressed into a zip archive using `cd build/sourcery; zip -r -X ../sourcery-#{podspec_version}.zip .`
2. Starting 2.1.4, releases are compressed initially by a shell script:
```bash
  pushd $CLI_DIR
  TAG=$GITHUB_REF_NAME
  FILENAME="sourcery-$TAG.zip"
  zip -r -X $FILENAME .
  mv $FILENAME "${HOME}/"
  popd
``` 
**and then** additionally by a GitHub action (like [here](https://github.com/krzysztofzablocki/Sourcery/actions/runs/7622572469)) - this is a default behaviour of the GitHub action as [documented here](https://github.com/actions/upload-artifact/tree/v3/#zipped-artifact-downloads).

Now, the problem comes down to human action:

1. When I download artifacts from the release GH action, I unzip it to get rid of "double-zippage"
2. Then, I archive a folder named `sourcery-x.y.z`, as compared to the bash script and to the old way with rake, does not exactly match how it is supposed to be done.
3. Then, I upload the archive

Afterwards, problem with cocoapods appears, where file path cannot be guessed correctly from the `podspec` file because this part is quite sophisticated to debug and understand.

**Comment by art-divin** [comment]
Release 2.1.7 is being prepared, will fix the issue.

**Comment by art-divin** [comment]
brew 2.1.7 version is being verified, then it'd be merged and become available. Related PR: https://github.com/Homebrew/homebrew-core/pull/160745

**Comment by arbyruns** [comment]
Thanks again for all the hard work in this. Really appreciate it.

**Comment by Shiaulis** [comment]
@art-divin can confirm, works perfect now in cocoapods 👌🏾
