### ISSUE TITLE
Add whitespace trimming configuration for Stencil templates

### ISSUE THREAD

**Issue by jgongo** [krzysztofzablocki/Sourcery#1271]
Stencil provides a way to [configure whitespace trimming](https://github.com/stencilproject/Stencil/blob/1aeeced65dc9f4652b74887e0e14e666efbda78d/Sources/Stencil/Environment.swift#L29) when creating the environment used to load the templates. In particular it allows you to configure [leading and trailing whitespace trimming with several options](https://github.com/stencilproject/Stencil/blob/1aeeced65dc9f4652b74887e0e14e666efbda78d/Sources/Stencil/TrimBehaviour.swift#L9).

It would be great to have some way to configure Sourcery whitespace trimming when using Stencil templates, so this configuration can be forwarded to the Stencil environment. (AFAIK there is no way to do it currently)

**Comment by art-divin** [comment]
Hi @jgongo ,

I have integrated the TrimBehaviour and its configuration and to my surprise it does not work at all.

Here are examples of the resulted generated code, after the integration:


|1|2|3|
:-:|:-:|:-:|
<img width="549" alt="Screenshot 2024-06-22 at 7 08 41 PM" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/f37c23dd-c065-4f8a-9fd4-83d412ab49b5">|<img width="537" alt="Screenshot 2024-06-22 at 7 08 20 PM" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/7dac9df1-a46c-4298-95c7-6285286fd83b">|<img width="339" alt="Screenshot 2024-06-22 at 7 08 01 PM" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/7a53f828-fe10-436f-80d5-c112c7aa9cd3">


I would close this issue because even though integration is working, the generated code is malformed, and so it would be useless.

**Comment by jgongo** [comment]
Ok, thank you very much!!
