### ISSUE TITLE
[Bug] Failed to resolve dependencies (SPM issue)

### ISSUE THREAD

**Issue by rafattouqir** [krzysztofzablocki/Sourcery#1276]
# Scenario: 
Trying to add Sourcery(exact version 2.1.7) as dependency via `Xcode->Project->Package Dependencies`

# Error:
`Failed to resolve dependencies Dependencies could not be resolved because package 'sourcery' is required using a stable-version but 'sourcery' depends on an unstable-version package 'swift-package-manager' and root depends on 'sourcery' 2.1.7.`

# Screenshot:
<image src="https://github.com/krzysztofzablocki/Sourcery/assets/2104659/9cad7386-60c0-47a1-9a15-43de8994e3fb"/>

**Comment by Liquidsoul** [comment]
I've stumbled on the same issue while trying to integrate Sourcery as a Plugin in an SPM package.

This issue was introduced with the integration of `swift-package-manager` as a dependency. Since SPM is not _really_ released as a package with semantic versioning, it is not possible to use a "stable" version of it. I did not find a workaround on this so maybe we need to rollback what was introduced [here](https://github.com/krzysztofzablocki/Sourcery/pull/1184) to restore the plugin functionality.

BTW, the changelog may need to be updated because it states that the SPM feature was introduced in `2.1.0` but the issue begins at `2.0.3`, the SPM config feature was introduced at 51290a59d80436a00bf5f820da9bd33654c6ed15 which is before the `2.0.3` tag.

**Comment by michalnowak061** [comment]
up

**Comment by rafattouqir** [comment]
@krzysztofzablocki did you get the time to look into this issue?

**Comment by art-divin** [comment]
👋🏻  Hello 

I am looking into this issue, thank you for reporting! Trying multiple approaches, let's see what would work.
⏲️

**Comment by art-divin** [comment]
#1280 should resolve this issue
