### ISSUE TITLE
Generated code doesn't compile if returning type starts with the "any" keyword

### ISSUE THREAD

**Issue by mol-ideals** [krzysztofzablocki/Sourcery#1310]
// Given
```
// sourcery: AutoMockable
protocol Repository {
  func loadData() -> any Publisher<String, Error>
}
```

// Generated code:
```
class RepositoryMock: Repository {
  ...
  var loadDataReturnValue: any Publisher<String, Error>!
  func loadData() -> any Publisher<String, Error> {
  ...
  }
}
```

This line `var loadDataReturnValue: any Publisher<String, Error>!` doesn't compile. The type needs to be placed inside the round brackets. This does compile - `var loadDataReturnValue: (any Publisher<String, Error>)!`

**Comment by art-divin** [comment]
Thank you very much for reporting @mol-ideals 👍🏻 

Will be fixed for 2.1.9 release.

**Comment by art-divin** [comment]
Hello @mol-ideals ,

it seems like you are using an older version of Sourcery.
Since a couple of versions - specifically, since 2.0.3 release, generated code:

1. supports `any` (mostly thanks to @paul1893 's work ❤️)
2. and since 2.1.8, Sourcery supports CVarArg in methods, and so, the naming of generated methods and variables was changed and now includes types, i.e. in 2.1.8 variable `loadDataReturnValue` is named `loadDataAnyPublisherStringErrorReturnValue` and indeed, return value is `(any Publisher<String, Error>)!`


Feel free to try using a later version of Sourcery and re-open this issue, in case the issue would persist.

**Comment by mol-ideals** [comment]
@art-divin  That's very strange. I was using 2.1.8 to reproduce it. At least I think so.
<img width="521" alt="Screenshot 2024-03-28 at 21 49 47" src="https://github.com/krzysztofzablocki/Sourcery/assets/145431622/ae1d1cab-449c-433a-8f29-1b3f60bb5cd1">
The title says it's generated via 2.1.8. For clarity I've tried reinstalling sorcery but it didn't change anything
<img width="838" alt="Screenshot 2024-03-28 at 21 54 12" src="https://github.com/krzysztofzablocki/Sourcery/assets/145431622/a3882e0d-107a-4ddc-b167-983859948990">

If 2.1.8 generates a different output for you the only theory I have is that somehow my older version is still alive.. but I can't see anywhere.
I installed sorcery via Homebrew if it matters

**Comment by art-divin** [comment]
@mol-ideals ,

there's nothing strange in particular, but it seems like the `stencil` file which is used in your setup is from an older version of Sourcery. Please check that one file, and update it. The newer version of this file is located under `Templates/AutoMockable.stencil` in the distributed release archive.

**Comment by mol-ideals** [comment]
Thank you @art-divin It worked!
