### ISSUE TITLE
Strip excess whitespace

### ISSUE THREAD

**Issue by radex** [krzysztofzablocki/Sourcery#155]
It can be quite difficult to read Sourcery-generated code because of all the excess whitespace.

Any line that has nothing but Stencil conditions/loops/etc leaves an empty line in generated code. There could be a rule that such lines are ignored completely — empty lines would be preserved only if the line is all-whitespace in stencil code.

In perfect world, indention levels would also be adjusted to look right, but that might be more difficult to do.

**Comment by ilyapuchka** [comment]
I think this was supposed to be covered by https://github.com/SwiftGen/StencilSwiftKit that we are using now @alisoftware

@radex it feels like the only way to fix that and preserve readable templates is to run swiftlint  autocorrect (or what ever linter/formatter you want) with whitespaces and empty lines rules enabled on generated code.

**Comment by krzysztofzablocki** [comment]
Its already gone in 0.5.5, what version were you running @radex ?

**Comment by radex** [comment]
Oh! It is indeed. My mistake!

**Comment by AliSoftware** [comment]
Note that the workaround I use in StencilSwiftKit will not be needed anymore when Stencil hits 1.0 as Kyle planned to address that problem differently in the future (one proposed way being copying ejs style, using `{%- for … %}` instead of `{% for … %}` with the minus sign to tell to remove newlines so that you can control them for each one). But for now this hasn't been implemented in Stencil yet, so my workaround in StencilSwiftKit is still useful.

**Comment by mariotaku** [comment]
Is this available for swifttemplate files?

**Comment by ilyapuchka** [comment]
Yes, its available with `<%_` and `_%>` tags. Check out docs to find out more - https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html

Ilya Puchka

Отправлено с iPhone

**Comment by ypaulovich** [comment]
I was searching a lot for the way of macros creation without new lines and didn't found anything.
There is solution:

{% macro Foo bar %}{#
#}{{ bar.baz }}{#
#}{% endmacro %}

{##} is comment placeholder so code will be more readable and will not produce newlines
