### ISSUE TITLE
Ideas for better name that avoids linguistic ableism

### ISSUE THREAD

**Issue by jhersh** [krzysztofzablocki/Sourcery#2]
Congrats on a supremely neat project! I wish only that it had a better name.

> Ableist language is any word or phrase that intentionally or inadvertently targets an individual with a disability... Examples of ableist language include “crazy,” “insane,” “lame,” “dumb,” “retarded,” “blind,” “deaf,” “idiot,” “imbecile,” “invalid (noun),” “maniac,” “nuts,” “psycho,” “spaz.”
>
> Each of these words, when used flippantly, can be extremely insulting to individuals who find themselves with physical (“lame,” “invalid,” “dumb”) or mental (“crazy,” “retarded,” “psycho”) disabilities.

([via here](http://thoughtcatalog.com/parker-marie-molloy/2013/10/15-crazy-examples-of-insanely-ableist-language/))

Naming is a Hard Problem™ and I'm guilty of using this language too. I would encourage you to consider a new name while this project is still new. Thanks!

**Edit:** From your own [Code of Conduct](https://github.com/krzysztofzablocki/Insanity/blob/master/CODE_OF_CONDUCT.md):

> Examples of behavior that contributes to creating a positive environment include:
> 
> Using welcoming and inclusive language
> ...
> Showing empathy towards other community members

**Comment by krzysztofzablocki** [comment]
Naming is indeed hard, I took the name `Insanity` from the famous Quote that I cite in the readme header, when I considered using name `KZCodeGen` or similar then some German folks come to me and complain about what `KZ` means in Germany so it's hard finding something that works for everyone.

Maybe you have any ideas how we could name this different?

**Comment by krzysztofzablocki** [comment]
How does MetaSwift sound?

**Comment by jhersh** [comment]
I think those are both excellent names, particularly the latter.

**Comment by ilyapuchka** [comment]
May I humbly suggest "Sorcery" or "SourceKitchen"? 😉

**Comment by dannyomo** [comment]
One chap mentioned "PreFlight": https://twitter.com/ambrstr/status/808078591732908032

**Comment by krzysztofzablocki** [comment]
just Meta (without Swift) actually sounds pretty good as well, especially when using it in context 'Meta is so meta that it generates its own code'

**Comment by jeremiegirault** [comment]
Maybe Check homebrew availability on such common words?

**Comment by LasseStorholt** [comment]
Meta works, but I actually really liked the name "Insanity". I saw a tweet about it and instantly clicked it.  It was bold, a bit crazy, and for me it described the project quite well. Especially that is was so "crazy" that it used itself to code-generate  boilerplate ;)   
   
"This and that... for Dummies" seems to work, so you have to be _that_ careful in selecting the name imho.

**Comment by krzysztofzablocki** [comment]
I did brew search and didn't see anything under:
- meta 
- swiftception
- sorcery
- preflight

@LasseStorholt yeah, but a few different people raised the concern about the name, this is a good read http://www.autistichoya.com/p/ableist-words-and-terms-to-avoid.html

I'd rather rename this and make more people feel welcomed in the community so we can grow it together, rather than keep to old name and alienate or make people uncomfortable

**Comment by fbartho** [comment]
In addition to the above, here are some ideas to make the first choices look better:
- SwiftFactory
- SwiftFlate - (inflate)
- SwiftPress
- SwiftDRY - (Don't Repeat Yourself)
- SwiftHose - (Keep D.R.Y. With the Swift hose!), SwiftCascade

**Comment by JegnuX** [comment]
Why note **SwiftWings** ? 🙂

**Comment by AliSoftware** [comment]
* `SwiftCeption`
* `Metabolism` (h/t @kaishin) : _set of life-sustaining chemical transformations within the cells of living organisms_

**Comment by artemstepanenko** [comment]
@krzysztofzablocki is there some good sounded Polish word related to the topic?

**Comment by krzysztofzablocki** [comment]
@artemstepanenko none that comes to mind, I'm liking `Metamorph`

**Comment by LasseStorholt** [comment]
I understand your concern @krzysztofzablocki, so here´s a suggestion that keeps some of the craziness of the original name. What about **Swiftsanity** ?

**Comment by AliSoftware** [comment]
I'm not an expert on that matter as I'm not concerned personally, but wouldn't `SwiftSanity` have the same ableism problem as `Insanity`?

**Comment by ivmirx** [comment]
I recently discovered that there's a bird similar to swift, called [swiftlet](https://en.wikipedia.org/wiki/Swiftlet).

There's only one Swift repo called "swiftlet" and it has zero stars, so in my opinion it could be a great name for something meta for Swift like your project.

**Comment by DarthMike** [comment]
Here's my suggestion; I like 'Sorcery' but with a twist: **Sourcery**. Links to `source` and a [great book](https://en.wikipedia.org/wiki/Sourcery).

**Comment by istx25** [comment]
I like Sourcery, Meta and Metamorph. Let's avoid any kind of ableist language or plays on ableist language. Sanity means "sound mental health." Is that the message we want to convey with SwiftSanity? I understand that some people here like the name Insanity but that's because it hasn't been used against you. There's privilege there and please recognize that. I'd love to use this project. Super cool tool but I won't until the name is changed and I imagine there's many who feel the same.

**Comment by istx25** [comment]
Also let's avoid adding "Swift" to the name too. I saw a blog post once that said to not reverence the language in the name unless there's multiple like "Sourcery-Swift" "Sourcery-Ruby" etc.

**Comment by krzysztofzablocki** [comment]
@istx25 Totally agree on all points

**Comment by istx25** [comment]
But my vote would be for Sourcery. I **really** like the name. I'd also like to rid the README of ableist language as well. Lot's of use cases of crazy and whatnot. Let's improve this project so everyone can enjoy it and be comfortable (or try our best).

**Comment by istx25** [comment]
Also, I had someone say something *interesting* to me. It's a fair point and I'm posting it because they were uncomfortable doing so: **You want people to use the tools you build, you don't want people to think you're the tool.** It's a bit outlandish but it's true. A lot of talent in the tech industry has mental health issues and "but I like the name Insanity" only perpetuates ableism. We can use this project as an example for the future where a mistake was made (due to language barrier or whatever else) and we made the change for the better. It won't go unnoticed and people, like myself, will appreciate the effort to correct the mistake. 

I'd love to even get more involved in this project if you need the help, to refactor the name throughout, maintain, etc.

**Comment by krzysztofzablocki** [comment]
@istx25 yeah the crazy wording was just playing on the name, we are going to remove it along with the rename, I literally didn't know what ableist means when I wrote this so this was educational and we should definitely try to avoid alienating anyone as that was never my intention

**Comment by istx25** [comment]
Totally fair! We (or at least I'm not) trying to *attack* you. I want this feedback to be as constructive as possible so we can rename and build on this great project. You've done a lot of great work and I would hate to see it tainted or not get the (positive) attention it deserves due to the name. I know there are a lot of differences between `$language` and English which often trips up people. Everything from ableist language to pronouns (like she/her, he/him, they/them) all work differently.

**Comment by krzysztofzablocki** [comment]
I just feel stupid for not knowing it, anyway we can correct this 👍 

I like `Metamorph` and `Sourcery` the most, made a twitter poll so people can vote https://twitter.com/merowing_/status/808342488389980160

**Comment by michalciurus** [comment]
Metagen or Mutagen or something similar

Fom meta and generate and mutate

**Comment by sahandnayebaziz** [comment]
+1 @krzysztofzablocki being so open to feedback and input from the community :)

**Comment by fbartho** [comment]
I like Sourcery the most, but there's also: http://getsourcery.com so… maybe that name is taken?

Meta is great, but I think Mutagen, Metamorph actually drifts away from the meaning of Meta-programming, and it implies turning your caterpillar into a butterfly. I think Metagen avoids those problems if you're looking for a longer name.

**Comment by istx25** [comment]
In my opinion, duplicate names are okay if they're completely different and that website seems to be completely different and unrelated to what this is. It's an open source project after all...

**Comment by ilyapuchka** [comment]
Swift was also tacken already, at least by the time it was releases, and even two times 😄

**Comment by krzysztofzablocki** [comment]
`Sourcery` is fine, I already reserved pod name but waiting for poll results

**Comment by kzaher** [comment]
Loved the name ... :) Will miss it. I'm sure new one will be even better.

**Comment by JimRoepcke** [comment]
There's really nothing insane about needing this tool, it's simply helps developers deal with the reality of writing Swift projects. One naturally ends up having to write a lot of boilerplate to deal with the type system.

How about "Reality" instead?

**Comment by JimRoepcke** [comment]
And wow, calling him a tool wasn't a very nice.

**Comment by istx25** [comment]
The word insane means severely mentally ill. So you're correct. This project isn't severely mentally ill. It's really cool though! And I wasn't calling him a tool. I said people will perceive him as one and I don't want that. As I mentioned, I want this project to get the attention and use it deserves and when it's renamed, I'll probably use it and contribute back a lot.

**Comment by krzysztofzablocki** [comment]
Project has been renamed to Sourcery, 0.3.0 version is available under Sourcery podspec now, hope more people can contribute now ;)

**Comment by lazerwalker** [comment]
I hope this isn't just adding extra noise, but I wanted to chime in and say I'm _really_ pleased and impressed with how this whole issue was handled. Someone raised a thoughtful point, everyone was civil and kind, and change happened super promptly. I wish this was the norm rather than the exception, but excellent job nonetheless :).

**Comment by Flame2057** [comment]
This pull request is retarded
