### ISSUE TITLE
Private/Fileprivate types unavailable?

### ISSUE THREAD

**Issue by robertjpayne** [krzysztofzablocki/Sourcery#200]
If you have:

Model.swift:
```
class Model {
}
private struct Triggers {
    var name: String
}
```

Template.stencil:
```
{% for type in types.all %}
// {{ type.name }}
{% endfor %}
```

The private type is never emitted, unsure if this is a source kit limitation or a sourcery issue?

**Comment by krzysztofzablocki** [comment]
we filter them out right now because private / fileprivate can only work if you use our inline generation feature, otherwise it won't compile

**Comment by robertjpayne** [comment]
@krzysztofzablocki in my use case I'm looking to use a private type as metadata to generate a public interface.

For example:

```
class MyViewModel : ReactiveTriggers {
    private struct Triggers {
        let onNameChanged: String
    }
}
```

Which I'm using to generate a `var onNameChanged: Signal<String, NoError>` from ReactiveSwift.

**Comment by krzysztofzablocki** [comment]
we need to figure out a sensible way to access private properties anyway because it can be useful in inline generation, @ilyapuchka do you reckon we should include private stuff now and just ask people to use filters e.g. `types.all|nonPrivate`?

**Comment by ilyapuchka** [comment]
I think with introducing of inline generation it makes more sense to stop filtering private declarations. The case that @robertjpayne described to use private marker protocol, so that you don't pollute public interface of your framework for example, also make sense. I also like your idea of using filter, I would just call them according to access levels, if you need to filter everything that is not private we will have `!private` automatically.
