### ISSUE TITLE
Templates currently can't express all logic

### ISSUE THREAD

**Issue by conradev** [krzysztofzablocki/Sourcery#22]
I have been trying to do things like this:

```swift
{% for type in types.implementing.AutoEquatable %}
extension {{ type.name }}: Equatable {}

func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
    {% for variable in type.storedVariables %}
    {% if variable.type implements Equatable or variable.type implements AutoEquatable %}
    if lhs.{{ variable.name }} != rhs.{{ variable.name }} { return false }
    {% endif %}
    {% endfor %}
    return true
}
{% endfor %}
```

or this:

```swift
{% for enum in types.enums where enum.name beginswith Gallery %}
extension {{ enum.name }} {
  static var count: Int { return {{ enum.cases.count }} }
}
{% endfor %}
```

and while operators like `where ... beginswith` and `if ... implements` are certainly possible to add to the template language, won't this project be hindered by the fact that the template language is not Turing-complete? Would it be possible to implement a library to build a Swift AST from Swift?

**Comment by krzysztofzablocki** [comment]
Stencil implementation we have here is not yet tweaked for more native code generation, we are actually splitting `SwiftGen` Stencil related extension into separate framework for Swift code generation and both tools will be using it. 
There are plenty of more useful nodes coming like `set`, `map` and `function` `call` that will significantly extend what's doable to express here.

But even so, I'm keeping the `Parser`, `Models` and `Generator` separate, because I've been experimenting with some other ideas, like generating code via native Swift by just calling `swiftc` and feeding it all model types as definitions. Is that something you'd like to explore, or think could be a better approach? 

Right now I'm focusing most of my time on improving the `Parsing` and `Model` reflections, both functionality from templates you are showing we can support with small changes to `Type` and a few extra nodes, for example we could modify the first sample by the following:

- Modify Variable to expose something like existing `TypesReflectionBox` instead of name
- Add `or node`

```swift
{% for type in types.implementing.AutoEquatable %}
extension {{ type.name }}: Equatable {}

func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
    {% for variable in type.storedVariables %}
    {% if variable.type.implements.Equatable or variable.type.implements.AutoEquatable %}
    if lhs.{{ variable.name }} != rhs.{{ variable.name }} { return false }
    {% endif %}
    {% endfor %}
    return true
}
{% endfor %}
```

**Comment by ilyapuchka** [comment]
Actually `or` is already supported by Stencil 0.7.0. `{% for %}` tag also now supports filter, but it looks like there is no standard filter like `beginesWith`, so we will need to add it. Then it will look like this I think:

```
{% for enum in types.enums|beginswith:"Gallery" %}
extension {{ enum.name }} {
  static var count: Int { return {{ enum.cases.count }} }
}
{% endfor %}
```

Btw @krzysztofzablocki do you think we should just add our custom filters as soon as we need them or contribute to Stencil instead? Would be cool if Sourcery will drive improvements in other projects 😀

**Comment by krzysztofzablocki** [comment]
@ilyapuchka we want to extract part of @alisoftware SwiftGen stencil extensions into separate framework and link both SwiftGen and Sourcery to it, then we can add things that make sense for Swift code-generation and both tools can leverage them

**Comment by kzaher** [comment]
Hi guys,

I really like this project, but it would be a lot easier for me to use it if I could just use normal Swift code for writing templates

>But even so, I'm keeping the Parser, Models and Generator separate, because I've been experimenting with some other ideas, like generating code via native Swift by just calling swiftc and feeding it all model types as definitions. Is that something you'd like to explore, or think could be a better approach?

This would be awesome, are there any plans to support this?

It seems to me it's really simple to translate

```
{% for enum in types.enums.filter { $0.hasPrefix("Gallery") } { %}
extension {{ enum.name }} {
  static var count: Int { return {{ enum.cases.count }} }
}
{% } %}
```

Into 
```
// some plumbing Swift code

for enum in types.enums.filter { $0.hasPrefix("Gallery") } { 
    print("extension ")print("\(enum.name)")print("{\n  static var count: Int { return ")print("\(enum.cases.count)")print(" }\n}")
}

```

It seems to me that the most complex part is serializing metadata info, but that serialization code could be generated using this project :)))

🙏 support this

Can this at least be supported as some kind of alternative mode?

**Comment by krzysztofzablocki** [comment]
@kzaher pretty much what I was doing that, parser / command line works without changes, and I just code-generate Type definitions as the `plumbing code` and then it's prefixed between your template code and compiled via `swiftc`

**Comment by kzaher** [comment]
> @kzaher pretty much what I was doing that, parser / command line works without changes, and I just code-generate Type definitions as the plumbing code and then it's prefixed between your template code and compiled via swiftc

I was assuming you were :)

**Let me just first say this out loud. I'm not advocating to drop stencil. I'm just advocating to make my life easier and also support Swift templates :)**

The basic pain point is that it's another different language I need to learn ... again.

css - it's declarative, totally different then js, it would be good idea to pull styles in one place, fine (although that can also be challenged, but fine)
html - declarative presentation, fine
xaml - html doesn't fit well with XXX world, grrr, well ok, it looks like xml and html and has embedded C#
xslt - there are safety concerns allowing arbitrary code execution on server, ok, I can understand why
...

From far away it looks like Swift, but I can't use all of the normal Swift syntax and libraries. I'm not against learning new things and languages, but that usually makes sense for me when the benefits outweigh the costs.

I understand your side that stencil has slightly more readable syntax because it doesn't have all the `{`, `"`, `[`, but every time I see

```
types.implementing.AutoEquatable
```
**my brain is struggling to understand what is the return value of that and what operations can I perform on the result.** 

The only way to know is to constantly look at the docs. And there are two docs. API of this project, stencil docs + understanding how do they integrate and what is supported. Since this project is forking stencil probably, then I have no idea even what docs to look at.
If I'm lucky, I'll find what I'm looking for. If I'm not, then I'll need to figure out some workarounds or wait for some PR to be merged.

I could theoretically learn everything by heart and skip the tedious docs browsing, but usage patterns aren't really suitable for learning something thoroughly.

The basic use pattern should be write your templates and forget about them. Then after a month, write some more, then forget about them. If that is not the pattern, then it's not boilerplate :)

Because I'm currently not using stencil on other projects I would need to learn it, then probably forget it since this was the only use case, then relearn it ....

Yes, I understand it's simple language, but I'm not sure what is `|beginswith:"Gallery"`. 
What is `|`, is `beginswith` a method? What is the precedence? Can I use `(` to change precedence?
It looks Turning complete, but have no idea can I create a convenience method or extension to reuse inside the template?
What if I have some functionality or extensions that I want also reuse across templates, can I write simply `import MyXXXExtensions`, I guess not, but I could if Swift templates were supported.

Js community writes templates in js, pyhon community in python probably, .NET in C#, ...

I was using ObjC for years, but I would never advocate to additionally support ObjC :), but Swift is really nice and readable.

If you could also support Swift templates, I would really enjoy using them and it would make using this project seamless for me.

As a bonus point, you could change syntax slightly so people can even use autocomplete and Xcode for writing templates, so no docs learning is needed:
```
for enum in types.enums.filter { $0.hasPrefix("Gallery") } { /**}
extension **/ p(enum.name) /** {
  static var count: Int { return **/ p(enum.cases.count) /** }
}
 }**/
}
```
... but ok, this is far fetched, I understand :)

**Comment by AliSoftware** [comment]
> What if I have some functionality or extensions that I want also reuse across templates, can I write simply import MyXXXExtensions, I guess not

Actually you soon will be able to. Stencil contains a `{% import xxx %}` tag to import other templates already, and when we finish merging the Stencil tags added by SwiftGen into a dedicated framework that Sourcery can use too, it will also have tags to define functions/macros and call them later.

**Comment by kzaher** [comment]
Hi @AliSoftware ,

love SwiftGen. Please don't feel like I'm fighting Stencil, but instead advocating to add optional Swift support also. I've seen stencil is used extensively in SwiftGen.

When I've seen this project I was so excited, it was exactly the thing I needed but never found time to build.

I'm trying to implement it in my project and I'm **really struggling because I can't express things that would be trivial to express in Swift**.

Disclaimer, I've only read https://stencil.fuller.li/en/latest/templates.html#comments and I'm poor at 
reading docs.

Here are some examples of practical problems that would all go away if I could just use Swift

```
{% for type in types.enums.implementing.AutoEquatable %}
    extension {{ type.name }} {
        public static func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
            switch (lhs, rhs) {
            {% for case in type.cases %}
            {% if case.associatedValues.count == 0 %}
                case ({{ case.name }}, {{ case.name }}): return true
            {% else %}
                case let ({{ case.name }}({% for associatedValue in case.associatedValues %}lhs_{{ associatedValue.name }}, {% endfor %}), {{ case.name }}({% for associatedValue in case.associatedValues %}rhs_{{ associatedValue.name }}, {% endfor %}):
                {% for associatedValue in case.associatedValues %} if lhs_{{ associatedValue.name }} != rhs_{{ associatedValue.name }} { return false }
                {% endfor %}
                return true
            {% endif %}
            {% endfor %}
            }
        }
    }
{% endfor %}
```

I can't just use case change, but have to use this ugly `lhs_{{ associatedValue.name }}`. Yes, I know, you can add it, but the point is not can it be added but can user freely extend the templates without changing the tool itself.

I have no idea how to only add commas only between associatedValues. `{{ case.name }}({% for associatedValue in case.associatedValues %}lhs_{{ associatedValue.name }}, {% endfor %}`. If this was Swift, I could just do string join with separator.
I've gave a shot to `{{case.associatedValues | joined ", "}}` and `{{case.associatedValues | joinedWithSeparator ", "}}` but none of them work.

I can't filter classes that implement this protocol or the other one so I have to duplicate templates.

In the upper example if you change `public static func == (` with `{{type.accessLevel}} static func == (` it doesn't cause a compile time error with line where the error is but crashes in runtime with 

```
2016-12-21 22:22:29.812 Sourcery[18893:1743938] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Sourcery.Enum 0x7fc2774587f0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key accessLevel.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7ed7b48b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff934ddcad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7ed7b3d9 -[NSException raise] + 9
	3   Foundation                          0x00007fff80842842 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 226
	4   Sourcery                            0x000000010b38ae51 _TFC8Sourcery4Type5valuefT15forUndefinedKeySS_GSqP__ + 881
	5   Sourcery                            0x000000010b38aff5 _TToFC8Sourcery4Type5valuefT15forUndefinedKeySS_GSqP__ + 53
	6   Foundation                          0x00007fff807144dc -[NSObject(NSKeyValueCoding) valueForKey:] + 283
	7   Stencil                             0x000000010b7be234 _TFV7Stencil8Variable7resolvefzCS_7ContextGSqP__ + 3892
	8   Stencil                             0x000000010b7bcd23 _TFC7Stencil16FilterExpression7resolvefzCS_7ContextGSqP__ + 99
```

... and yes, if you write 

```
{% for type in types.implementing.AutoEquatable %}
    {{type.accessLevel}}
```

it does work.

... and yes, I have a big template and I have spend some time figuring out where is the issue.

I've checked source code and `Enum` should have `accessLevel`.

Also, for some reason `types.enums.implementing.AutoEquatable` returns all enums for me. Don't know why.

**🙏 add Swift support**. I'm sure with time stencil will get better and better, but I just need this to work even if the code is not as pretty. 

The funny thing is that I don't think the example that I've presented would be that much less readable with Swift. Templates will always be ugly and unreadable no matter what. At least to me.

**Comment by kzaher** [comment]
Ok, found value `join`, looks like there is `capitalize`, have no idea for `accessLevel`, `AutoEquatable` has to be implemented in the same framework, so that solves part of issues.

**Comment by krzysztofzablocki** [comment]
@kzaher you should be using `--watch` daemon when writing templates as it allows you to write them in real-time and side-by-side with generated code + it recovers from template mistakes that lead to crashes in normal mode.

it's not `types.enums.implementing.AutoEquatable`, the types reflection is offering top level filter so it's `types.implementing.AutoEquatable`, to support `types.enums.implementing.AutoEquatable` we'd need to tweak the reflection type a little which sounds it might be useful. 
On current version you'd have to do something like:
```swift
{% for type in types.implementing.AutoEquatable %} {% if type.kind == "enum" %}
// Logic
{% endif %} {% endfor %}
```

**Comment by kzaher** [comment]
Hi @krzysztofzablocki ,

can you maybe share with me what is the best way to autoimplement Hashable and Equatable for enum. That's the last thing I need.


```
{% for type in types.implementing.AutoEquatable %} {% if type.kind == "enum" %}
    extension {{ type.name }} {
        public static func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
            switch (lhs, rhs) {
            {% for case in type.cases %}
            {% if case.associatedValues.count == 0 %}
                case ({{ case.name }}, {{ case.name }}): return true
            {% else %}
                case let ({{ case.name }}({% for associatedValue in case.associatedValues %}lhs_{{ associatedValue.name }}, {% endfor %}), {{ case.name }}({% for associatedValue in case.associatedValues %}rhs_{{ associatedValue.name }}, {% endfor %}):
                {% for associatedValue in case.associatedValues %} if lhs_{{ associatedValue.name }} != rhs_{{ associatedValue.name }} { return false }
                {% endfor %}
                return true
            {% endif %}
            {% endfor %}
            }
        }
    }
{% endif %} {% endfor %}
```

This is my best attempt. I've found `join` and `capitalize`. The problem with my solution is that I need to do `values.map { "lhs\($0)" }.joined(separator: ", ")`.

If I use `for` construct then I don't know how to remove trailing `,`. 
If I use `join`, I don't know how to do `"lhs\($0)"`.

**Comment by krzysztofzablocki** [comment]
once we have the extra nodes from @AliSoftware framework it will be simpler since we'll have map node :) for now I use simple separate statements, here is the body of the comparsion loop I've been using in NYT app:
```swift
func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
    switch (lhs, rhs) {
        {% for case in type.cases %}
        {% if case.hasAssociatedValue %} case (.{{ case.name }}(let lhs), .{{ case.name }}(let rhs)): {% else %} case (.{{ case.name }}, .{{ case.name }}): {% endif %}
            {% ifnot case.hasAssociatedValue %} return true {% else %}
                {% if case.associatedValues.count == 1 %}
                    return lhs == rhs
                {% else %}
                    {% for associated in case.associatedValues %} if lhs.{{ associated.name }} != rhs.{{ associated.name }} { return false }
                    {% endfor %} return true
                    {% endif %}
            {% endif %}

        {% endfor %}
        default: return false
    }
}
```

**Comment by kzaher** [comment]
Thnx,

how about for `Hashable`. I've found this hacky way with `0`.

```
return 0 {% for associatedValue in case.associatedValues %} ^ {{ associatedValue.name }}.hash {% endfor %}
```

... but would like to remove it. Is there any way to do this?

**Comment by krzysztofzablocki** [comment]
Word of caution: using `^` for hashing is not going to work well, I made that mistake in the past and we had bugs that were really hard to track, you need to use something else like djb or alternative algo, we based our on `boost::hash_combine` implementation, read more here: http://stackoverflow.com/a/27952689

Once we include the aformentioned `map` node this should be simple to get rid of, right now I also had the 0 prefix ¯\_(ツ)_/¯

**Comment by kzaher** [comment]
Thnx for the tip.

I guess I could rewrite hash to be something like:
```
{% for type in types.implementing.EnumAutoEquatable %}
// Enum auto hashable
extension {{ type.name }}: Hashable {
    public var hashValue: Int {
        switch self {
        {% for case in type.cases %}
        {% if case.associatedValues.count == 0 %}
            case .{{ case.name }}:
                return 1
        {% else %}
        {% if case.associatedValues.count == 1 %}
            case let .{{ case.name }}(value):
                var hash: Int = 5381
                {% for associatedValue in case.associatedValues %}hash = ((hash << 5) &+ hash) &+ value.hashValue
                {% endfor %}
                return hash
        {% else %}
            case let .{{ case.name }}(values):
                var hash: Int = 5381
                {% for associatedValue in case.associatedValues %}hash = ((hash << 5) &+ hash) &+ values.{{ associatedValue.name }}.hashValue
                {% endfor %}
                return hash
        {% endif %}
        {% endif %}
        {% endfor %}
        }
    }
}

{% endfor %}
```

Is there any way I could get associatedValue index so I can encode particular enum case ordinal in `hashValue`?

Is there something like `enumerated`?

**Comment by AliSoftware** [comment]
@kzaher inside a `{% for %}` block, Stencil gives you access to a `forloop` dictionary variable containing the sub variables `forloop.first` (true if first iteration), `forloop.last` (true if last iteration) and`forloop.counter` (containing the current iteration number)

You can thus use `{{ forloop.counter }}` to get your associated values index while iterating over them.
You can also use things like `{% if not forloop.last %}, {% end if %}` to only add a comma if it's not the last iteration. That should allow you to solve your problem until we integrate the `{% map %}` node in a future version.

**Comment by kzaher** [comment]
Thnx

**Comment by krzysztofzablocki** [comment]
0.5.2 has experimental support for Swift templates which means we have access to Turing-Complete language, thanks @kzaher
