### ISSUE TITLE
Detect typealiases

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#23]
Will it be helpful if parser will be able to detect typealiases and maybe store them in a property of a `Type` just like contained types and global aliases in `types.typealiases`collection?

**Comment by krzysztofzablocki** [comment]
I think it will because I think is important that if someone is trying to access a type via typealias, it needs to resolve to the meta information of the original type, which will be crucial. If you want to pick it up, I added some convenience for extracting substrings in last commit.

One thing that's related and something that @conradev wanted to access in #22, is the fact that Variables shouldn't be storing `type` as `String`. 

Instead we should create/reuse the approach I created for `TypesReflectionBox`, that way we can query variable type for meta information. This would allow us to do things like:

```swift
{% if variable.type.implements.Equatable %} compare {% endif %}
```

**Comment by ilyapuchka** [comment]
To start I've created #26. Let me know if you think I'm moving in a right direction or not.

**Comment by krzysztofzablocki** [comment]
The code looks good, but I think it would be nicer to add that resolution logic to `uniqueTypes` function, that way the `Models` have no relation to `Generator` (which means in the future we could replace Stencil with something else if we wanted to), and `Parser` creates fully configured `Models`, what do you think?

**Comment by krzysztofzablocki** [comment]
Closing this as we already have some typealias support but are working on more improvements in #38
