### ISSUE TITLE
Add methods reflection

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#24]
To be able to use Sourcery to generate code for such things like test doubles or dependency injection container it's vital to be able to access information about methods defined in class (or even on a protocol?).

To start method can be modeled like this:

```swift
class Method: NSObject {
  class Parameter: NSObject {
     var argumentLabel: String
     var parameterName: String
     var type: String
  }
  var parameters: [Parameter]
  var shortName: String //does not include external parameters names
  var fullName: String
  var returnType: String
  var accessLevel: AccessLevel
  var isStatic: Bool
  var isClass: Bool
}
```

Then in template it might be used something like this (taking [Dobby](https://github.com/trivago/Dobby) as an example):

```
{% for type in types.classes %}
  class {{ type.name }}Mock: {{ type.name }} {
    {% for method in type.methods %}
    override func {{ method.shortName }}({% for parameter in method.parameters %}{% if parameter.argumentLabel %}{{ parameter. argumentLabel }} {% endif %}{{ parameter.parameterName}}: {{ parameter.type }}{% endfor %}) -> {{ method.returnType }} {
      /* record a method call */
    }
  }
{% endfor %}
```

**Comment by krzysztofzablocki** [comment]
Another good idea, we should avoid using tuple as that might not be accessible via reflection. We'll just create an inner type for the `MethodParameter`.

I wonder if I should add something to readme/contributing doc about why the code here is more of an objective-c rather than how you'd write real swift code, due to the fact it's using it allows us to leverage the runtime in templates.

**Comment by krzysztofzablocki** [comment]
#72 closes this
