### ISSUE TITLE
Release 0.6.0 provides the previous binary version

### ISSUE THREAD

**Issue by iDonJose** [krzysztofzablocki/Sourcery#284]
The [latest release](https://github.com/krzysztofzablocki/Sourcery/releases/download/0.6.0/Sourcery-0.6.0.zip) uses the 0.5.9 binary version, just check /bin/Sourcery.app's version.

Thus using Sourcery through Cocoapods leads to use an older version and some of the latest features are missing.

**Comment by Antondomashnev** [comment]
Hi @iDonJose thanks for the catch 👍 
I've checked the 0.6.0 release tag in the source code and it seems the problem is because the `Current Project Version` in build settings is set to `0.5.9` but the functionality is the correct for the 0.6.0 version.

@krzysztofzablocki @ilyapuchka I think we can prevent the bug in the feature by updating the `rake check_versions task` 😄

**Comment by krzysztofzablocki** [comment]
I might have forgotten the metadata update, we should definitely automate this at some point

**Comment by Antondomashnev** [comment]
This can be closed, I guess.
