### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Joannis** [krzysztofzablocki/Sourcery#306]
I've tried getting Sourcery working on Linux as a test. SourceKit and SourceKitten can be compiled for Linux, I've already managed that, but the FileWatcher used in Sourcery seems to be the only library that doesn't support Linux. If Sourcery moves to SPM you could fetch all dependencies except the FileWatcher using SPM and compile it. `--watch` wouldn't work, but Sourcery would be working on Linux which is good for Server Side Swift development. Anywhere a feature isn't supported/supportable on Linux you can place a `#if !os(Linux)` or preferably `#if os(macOS) os(iOS) os(watchOS)`.

Just as an added note: I'm not suggesting this as a must for 1.0. But I'd definitely like this to be supported in the future.

**Comment by krzysztofzablocki** [comment]
FileWatcher pod is no longer used for Sourcery as I needed more powerful daemon, we'll just remove it completely (I thought I already did)

**Comment by Joannis** [comment]
I'm not sure if you've removed it. I might still be running too old code in my tests.

**Comment by damirstuhec** [comment]
@krzysztofzablocki Any updates on this? 🙇

**Comment by felix91gr** [comment]
We’re using [this watcher](https://github.com/felix91gr/FileSystemWatcher) to add support for Linux in SourceKittenDaemon. It’s a wrapper of the `inotify` C library present in the Linux kernel + a basic daemon.

**Comment by felix91gr** [comment]
Ponyboy47, the guy behind the original wrapper, has been developing a new FS Watcher [here](https://github.com/Ponyboy47/inotify). The guy really knows what he’s doing, so maybe that’s a better option. We’ll see.

**Comment by mxcl** [comment]
Hi, I need this for various reasons, would you accept the patch that removes `--watch` on Linux as for my use (and I think most other people too) we need Sourcery in our CI environments but we don’t need it as a workflow tool (on Linux at least).

**Comment by ilyapuchka** [comment]
@mxcl I guess this is acceptable for now, but why not just commit generated code instead of running Sourcery on CI?

**Comment by mxcl** [comment]
>  but why not just commit generated code instead of running Sourcery on CI?

Two reasons:

* Humans make mistakes, if I have to generate it manually, I'll forget.
* I don't like committing generated files (especially generated files that are only used for CI on two platforms out of six)

> I guess this is acceptable for now

Well, if you aren't cool with it then I'd rather not. Since maintaining something that core don't want is not fun.

**Comment by ilyapuchka** [comment]
I think it is fine as I suppose watcher does not work on Linux any way, but I didn't try it. @krzysztofzablocki you probably know better if thats the case?

**Comment by felix91gr** [comment]
I agree with @mxcl

Committing generated code seems like a very bad idea. The whole point of Sourcery is that the _canonical code_ are your macros. If you’re committing generated code, you’re not committing canonical code. I might be wrong, but that seems like a very bad idea.

**Comment by krzysztofzablocki** [comment]
@mxcl we'd be happy to accept a PR that enables Linux support, even without the watcher especially since its nice to have and not a critical feature 👍 

I totally agree with `Humans make mistakes, if I have to generate it manually, I'll forget.`, the whole idea behind Sourcery is to limit human mistakes as much as possible, its the driving principle for this project.

@felix91gr I do disagree on not committing generated files in most projects, but there are few reasons behind this:

-  I believe that you should always be able to fetch your repository and run it instantly without having to run `pod install` and things like that. 
- Sourcery generates the exact code you ask it to generate, its not opinionated and I think we should still review that code in our PR's, this is your production code after all, by commiting it you will see Diffs in the PR's
- If for some reason the tool would ever breaks on new version of Xcode / OSX, your code is still working and you can just move to maintaining it by hand like you did before using Sourcery

I definitely think that limiting human mistakes by having the codegen run with each build is more important than whether you commit the code or not, although I've been burned by not commiting it in the past so my recommendation is to do it for the above reasons :)

**Comment by ilyapuchka** [comment]
@krzysztofzablocki I could not explain it better, completely agree with all the points (the only thing is probably LinuxMain is really not that necessary to commit, but if so, I would consider it as exception). I think we should put it in README as general recommendation.

**Comment by mxcl** [comment]
K great, I'll spin up my docker.

**Comment by felix91gr** [comment]
@mxcl how did it go? I'm willing to help. I'm in need of generating LinuxMain files and already two people have pointed out to me that this is trivial with Sourcery 😅

Maybe we can make a PR to start enabling Linux support :)

**Comment by felix91gr** [comment]
Also: @krzysztofzablocki @ilyapuchka, what's left in general to enable Linux support?

**Comment by mxcl** [comment]
I made some progress but it was going to be a lot more work than I anticipated, mainly because Sourcery doesn't handle `#if os()` and I would need to make that work too.

**Comment by felix91gr** [comment]
Oh no :(

> mainly because Sourcery doesn't handle `#if os()`

How so?

**Comment by Tomaz-Vieira** [comment]
Hello, everyone
Do we have any progress with this? I'd be supremely interested in using Sourcery on Linux, and I'd also be willing to help if someone could give me some pointers.

**Comment by Nikoloutsos** [comment]
Any updates on linux compatibility?

**Comment by art-divin** [comment]
👋 Hi all

I have installed ubuntu VM through [tart](https://github.com/cirruslabs/tart/issues/62#issuecomment-1225956540) and updated to 22.04 according to [this guide](https://www.linuxtechi.com/upgrade-ubuntu-20-04-to-ubuntu-22-04/).

I had to run the following commands prior to being able to run `bundle install` in Sourcery:

1.  `sudo apt install libffi-dev`
2. `sudo apt install build-essential`
3. `sudo apt install libsqlite3-dev`

Then I was able to successfully run `bundle install`.

Unfortunately SourceryRuntime contains import of `CommonCrypto` which are binding codebase to Apple platforms.
I wonder if there's a way to cut these references out ❔

I'll continue investigation 🕐

**Comment by krzysztofzablocki** [comment]
We could drop CommonCrypto and use some replacement, I think this is only used for cache hash

**Comment by art-divin** [comment]
> We could drop CommonCrypto and use some replacement, I think this is only used for cache hash

Indeed, there's some replacement available in [swift-tools-support-core](https://github.com/apple/swift-tools-support-core), albeit being deprecated - [SHA256](https://github.com/apple/swift-tools-support-core/blob/ef2db24dbe7e39ebfabca2c10905909708c5738b/Sources/TSCBasic/HashAlgorithms.swift#L34)

**Comment by Joannis** [comment]
Or SwittCrypto

**Comment by art-divin** [comment]
👋🏻  Hey, a little update:

as it appears to be, there are a lot of issues compiling code under AST and other parts of code, mainly related to `@objcMembers` throwing an error on Linux.

Wrapping it into

```swift
#if os(macOS)
@objcMembers 
#else
#endif
```

helps, so I am continuing this journey.

**Comment by art-divin** [comment]
👋🏻 Hey all, a little update:

I was able to reduce number of errors down to a hundred or less, but now there are plenty in `Configuration.swift` and mostly related to `JavaScriptCore` framework.

Other changes I needed to make is to disable almost all `SourceryRuntime/Generated` extensions due to inheritance from `NSObject` and use of `@objc` annotations. This would take a while to automate I suspect 🤔  

My current plan is to make it buildable, although some features will be broken.

**Comment by art-divin** [comment]
👋🏻 Hey all, some news:

I was able to resolve all of the build errors in Sourcery, though some of the fixes I applied I'd need to refactor. At the moment I face these issues coming from `swift-llbuild`:
```
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld.gold: error: cannot find -lncurses
.build/checkouts/swift-llbuild/lib/llvm/Support/Unix/Process.inc:340: error: undefined reference to 'setupterm'
.build/checkouts/swift-llbuild/lib/llvm/Support/Unix/Process.inc:358: error: undefined reference to 'tigetnum'
.build/checkouts/swift-llbuild/lib/llvm/Support/Unix/Process.inc:362: error: undefined reference to 'set_curterm'
.build/checkouts/swift-llbuild/lib/llvm/Support/Unix/Process.inc:363: error: undefined reference to 'del_curterm'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by art-divin** [comment]
I figured it out, I needed to install `sudo apt-get install libncurses5-dev` and ... build is successful! Sourcery was compiled under Ubuntu! 🔥

**Comment by art-divin** [comment]
Hi all 👋🏻 

Linux Support #1188  is ready for review. What a ride! It works 🔥 🎆
