### ISSUE TITLE
The introduced swift templates caching using precompiled binary helper framework will not work because Swift lacks ABI stability.

### ISSUE THREAD

**Issue by eugeneego** [krzysztofzablocki/Sourcery#309]
#229 #240 
The user can have different Swift compiler version than that was used for compilation of `SourceryRuntime.framework`.
Currently Swift does not have ABI stability. All frameworks and the swift source code files should be compiled using the same compiler.
Also ABI stability is deferred from Swift 4 https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170213/032116.html

**Comment by ilyapuchka** [comment]
Hey @eugeneego 
Users who are using different version of swift compiler than the one used to build Sourcery binary (since the version with improved caching will be released) can build Sourcery from source code in this case. This will build SourceryRuntime framework with the same swift compiler version.

**Comment by eugeneego** [comment]
@ilyapuchka Sourcery uses CocoaPods for distributing and probably can compile SourceryRuntime framework during project build.

**Comment by ilyapuchka** [comment]
Currently with CocoaPods we distribute only release archive, not a source code. So to build runtime framework with CocoaPods will make us probably to include its source code into release archive, so that CocoaPods can use it to build the framework as a post step somehow. Or we will need to switch to distributing the whole source code instead of just release artefacts. But I'm not sure how it will behave in this case. Most likely it will link user project with SourcercyRuntime framework which is not needed at all and will require other hacks to disable that. And I'm not even sure if CocoaPods supports building binaries.

SourceryRuntime framework is used not only by the swift templates but also by Sourcery itself. Sourcery when it compiles swift templates (as a step of rendering) simply copy this framework from its  bundle to the build path of templates. To use different version of SourceryFramework in this case we will have to provide additional CLI argument for the path to this binary. 

Sounds for me like a lot of work and much more complicated setup comparing with building from source code.

**Comment by ilyapuchka** [comment]
I will close this for now, if you will have any further questions or suggestions feel free to reopen it.
