### ISSUE TITLE
Default implementation cause method duplication

### ISSUE THREAD

**Issue by ManWithBear** [krzysztofzablocki/Sourcery#326]
1. What version of Swift are you using (swift --version)?
    ```
    Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
    Target: x86_64-apple-macosx10.9
    Sourcery 0.6.0
    ```
2. What did you do?
    Protocol:
    ```swift
    protocol Magic {
        func doMagic(animated: Bool)
    }
    extension Magic {
        func doMagic(animated: Bool = true) { }
    }
    ```
    Template:
    ```
    {% for protocol in types.protocols %}
    {% for method in protocol.methods %}
    {{ method }}
    {% endfor %}
    {% endfor %}
    ```
    Generate:
    ```
    Method: name = doMagic(animated: Bool), shortName = doMagic, callName = doMagic, parameters = [MethodParameter: argumentLabel = Optional("animated"), name = animated, typeName = Bool, typeAttributes = [:], defaultValue = nil, annotations = [:]], returnTypeName = Void, actualReturnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, isConvenienceInitialiser = false, annotations = [:], attributes = [:]
    Method: name = doMagic(animated: Bool = true), shortName = doMagic, callName = doMagic, parameters = [MethodParameter: argumentLabel = Optional("animated"), name = animated, typeName = Bool, typeAttributes = [:], defaultValue = Optional("true"), annotations = [:]], returnTypeName = Void, actualReturnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, isConvenienceInitialiser = false, annotations = [:], attributes = [:]
    ```
3. What did you expect to see?
There should be just second method.

4. What did you see instead?
Two methods

Problem looks similar to #158, but here problem in default value for parameter.

**Comment by Antondomashnev** [comment]
Hi @ManWithBear thanks for creating an issue, I think you're right. The second method should override the first one. I will take a closer look on soon.

**Comment by ilyapuchka** [comment]
@ManWithBear I'm not sure that returning just one method is a correct behaviour. Method defined in the extension with default parameter value is not the same as method defined in the protocol declaration, even if its signature because of default value matches. If you implement this protocol on some type but call it without passing parameter - it will call method from extension, not your implementation in conforming type, unless you define default value there too, but then all these methods will be considered different and you will not be able to call implementation from extension.

What is your use case?

**Comment by Antondomashnev** [comment]
I can give my use case:
```swift
protocol ExternalViewer {
    static var name: String { get }
    static var bundleID: String { get }

    static func isAvailable(osxApplicationFinder: OSXApplicationFinder) -> Bool
    static func canView(snapshotTestResult: SnapshotTestResult) -> Bool
    static func view(snapshotTestResult: SnapshotTestResult, using processLauncher: ProcessLauncher)
}

extension ExternalViewer {
    static func isAvailable(osxApplicationFinder: OSXApplicationFinder = OSXApplicationFinder()) -> Bool {
        return isAvailable(osxApplicationFinder: osxApplicationFinder)
    }
}
```

So as you can see there is an extension for the method because I wanted to use dependency injection only in tests, but in other cases, the default parameter + default implementation is sufficient to reduce the code duplication. Eventually, I've ended up with the same problem as @ManWithBear. I haven't reported it because I also have doubts whether it makes sense to not return two methods or not. But right now I see maybe there is a common use case which not correct from the Swift Compiler perspective, but useful from the client one.

Maybe we can suggest the `annotation` in that case, but I encourage all of to think how we can make it easier to use Sourcery in such situation 😄

**Comment by ilyapuchka** [comment]
I got the use case of using default parameters values, but how do you want to use this in Sourcery template and what do you want to generate?

**Comment by Antondomashnev** [comment]
I can not copy paste the code what I wanted to achieve, but it's basically `AutoMockable` template code:
```swift
class ExternalViewerMock {
  var isAvailableCalled: Bool
  var isAvailableCalledParameter: OSXApplicationFinder
}
```

and currently I end up with:
```swift
class ExternalViewerMock {
  var isAvailableCalled: Bool
  var isAvailableCalledParameter: OSXApplicationFinder
  // And once again
  var isAvailableCalled: Bool
  var isAvailableCalledParameter: OSXApplicationFinder
}
```

**Comment by ilyapuchka** [comment]
Ok, got it, but I'm still not sure that returning just one method will be a correct solution, and one that will be easy to implement (what about methods with several parameters?). Maybe we should add a reference to where the method/property was defined (reference to `Type` object for extension) and then this can be used in the template to filter out methods or, as in this case, it may generate different variables.

**Comment by Antondomashnev** [comment]
> what about methods with several parameters?

I'm not sure what you mean here, because this will not compile for example:
```swift
protocol Foo {
  func bar(one: Int, two: Int, three: Int)
}

extension Foo {
  func bar(one: Int = 1, two: Int, three: Int)
  func bar(one: Int, two: Int = 2, three: Int)
  func bar(one: Int, two: Int = 2, three: Int = 3)
}
```
This what you were worried of or not exactly? 😄 

> Maybe we should add a reference to where the method/property was defined

I think the same idea was already proposed in https://github.com/krzysztofzablocki/Sourcery/issues/158 - `isDefinedInExtension`. But your idea is a bit generic - so each method will have a reference to which type it belongs? How could the filtration be done in the template then?

**Comment by ilyapuchka** [comment]
Filter can be applied using `kind` property or we can add `extension` filter similar to `struct`, `enum` etc.

**Comment by ilyapuchka** [comment]
And not only method can have this reference, it also can be applied for properties. And not only extensions can be referenced, but also types, this might be useful for some cases where we need to known in what class in inheritance chain the property is defined. This will make this reference property universal, not just a warkround to solve particular problem

**Comment by Antondomashnev** [comment]
@ilyapuchka I like the idea 👍, I think we can start implementing it. I could take this task for example.

**Comment by Antondomashnev** [comment]
@ManWithBear, in the upcoming release you'd be able to write something:

Protocol
```
protocol Magic {
    func doMagic(animated: Bool)
}
extension Magic {
    func doMagic(animated: Bool = true) { }
}
```

Template:
```
{% for protocol in types.protocols %}
{% for method in protocol.methods %}
{% if method.definedInExtension %} 
// MARK: - Defined in extension
{% else %}
// MARK: - Defined in protocol
{% endif %}
{{ method }}
{% endfor %}
{% endfor %}
```

That will generate:
```
// MARK: - Defined in protocol
Method: name = doMagic(animated: Bool), shortName = doMagic, callName = doMagic, parameters = [MethodParameter: argumentLabel = Optional("animated"), name = animated, typeName = Bool, typeAttributes = [:], defaultValue = nil, annotations = [:]], returnTypeName = Void, actualReturnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, isConvenienceInitialiser = false, annotations = [:], attributes = [:]
// MARK: - Defined in extension
Method: name = doMagic(animated: Bool 
= true), shortName = doMagic, callName = doMagic, parameters = [MethodParameter: argumentLabel = Optional("animated"), name = animated, typeName = Bool, typeAttributes = [:], defaultValue = Optional("true"), annotations = [:]], returnTypeName = Void, actualReturnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, isConvenienceInitialiser = false, annotations = [:], attributes = [:]
```

So you'd be able to distinguish between methods that are defined in extension or not. Moreover we have now the same for variables. Hope that will help you 😄
