### ISSUE TITLE
Option to disable output of version number in generated files header

### ISSUE THREAD

**Issue by danielr** [krzysztofzablocki/Sourcery#399]
For those people who like committing the generated files to version control (yes, I'm aware of the pros and cons), it would be great to have the option to exclude the version number from the header of the generated files. Otherwise every upgrade of Sourcery leads to meaningless changes in the working copy:

```
-// Generated using Sourcery 0.7.2 — https://github.com/krzysztofzablocki/Sourcery
+// Generated using Sourcery 0.8.0 — https://github.com/krzysztofzablocki/Sourcery
```

I guess this could be either a command line option, or an option in the config file (or both).

I'd be happy to contribute this myself in case it's deemed useful.

**Comment by Antondomashnev** [comment]
Hi @danielr I see your point, but from my perspective the version is something that may help eventually, as a reference I see that CocoaPods, for example, also writes version that generated `Podfile.lock`. 

@ilyapuchka @krzysztofzablocki what do you think about it?

**Comment by krzysztofzablocki** [comment]
I agree with @Antondomashnev, its helpful to have version there

**Comment by Antondomashnev** [comment]
@danielr I think we should keep the version number, and I really think it may help your team eventually 😄

**Comment by ilyapuchka** [comment]
Agree too, having version is valuable.

**Comment by ilyapuchka** [comment]
What we can do though is to provide an option to set custom header (with an option to set a version with a placeholder). It can

**Comment by dcacenabes** [comment]
Hi!
I know this ticket has been closed for many years now, but we're currently struggling with this. We use a cache mechanism to re-use precompiled versions of our modules. The tool computes a SHA based on the contents of the source files within a module. Since Sourcery includes the version in the autogenerated files, it causes the SHA to be different triggering a cache miss.

I understand that versioning can be of use to some people. Is there any chance you reconsider adding an option to make this configurable?

**Comment by art-divin** [comment]
Hello @dcacenabes ,

due to the importance of speeding up CI time and improving developer experience, which was rarely the case in the past,
I agree that we really should disable this part of the header from the generated files. It does not serve purpose these days anyways, as far as for the last year there was not a single bug fix, where this information helped in its resolution.

Let's reopen and quickly fix 👍🏻

**Comment by dcacenabes** [comment]
Hey @art-divin, if you want to go for removing it, I can contribute with a PR myself if it is ok with you :)

**Comment by art-divin** [comment]
Hey 👋

Would be greatly appreciated, in fact, just in time before 2.1.9 release!

**Comment by dcacenabes** [comment]
I just opened a PR, but I am not sure if I should have edited all the .generated files. Since they were being tracked under source control I decided to update them too.
https://github.com/krzysztofzablocki/Sourcery/pull/1309
