### ISSUE TITLE
Provide full type information for unwrappedType

### ISSUE THREAD

**Issue by danielr** [krzysztofzablocki/Sourcery#424]
Currently, `TypeName.unwrappedTypeName` returns a `String`. I'd argue that it should return a `TypeName` object, which encapsulates the whole type information of the unwrapped type. While this might not make a huge difference for normal optionals (because the unwrapped type info is available as part of the optional type directly), it does make a difference for double-optional variables. Currently there is no way to get to the actual type (name) object of the inner optional, you can just get it as a String.

I assume that the current limitation is due to the missing support for generics, but still wanted to file it as an issue here.

**Comment by art-divin** [comment]
Unfortunately, this is not possible to implement due to "chicken and egg" problem, i.e. `TypeName.unwrappedTypeName ` is non-optional, and so, it requires a `TypeName` instance which cannot be instantiated without the `unwrappedTypeName` argument, which must be allocated on the callee site as `TypeName(name:unwrappedTypeName:TypeName(name:......)`.

Closing.
