### ISSUE TITLE
How do I include the generated swift files into the Xcode automatically?

### ISSUE THREAD

**Issue by Sethuraman** [krzysztofzablocki/Sourcery#457]
Hi,

I have got my sources generating to a folder inside my project. This is my .sourcery.yml file 
```
sources:
  - ./Ayuda/
templates:
  - ./sourcery-templates/
output:
  ./Ayuda/GeneratedCode/
```

How to add any file getting created inside the GeneratedCode folder into the Xcode project automatiically? I have a Run Script section that generates my sourcery code for me.

Thanks
Sethu

**Comment by krzysztofzablocki** [comment]
Adding new generated files to pbxproj automatically? we don't support this, you'd have to use something like https://github.com/venmo/synx

**Comment by ilyapuchka** [comment]
I think it will do the opposite, remove files not included in the project.
But i think we can add this feature, we already use a pod that reads project file, it should support editing too. What do you think?

**Comment by krzysztofzablocki** [comment]
Do you want to tackle that? It's something few people asked for before

**Comment by ilyapuchka** [comment]
I'de like to play with it. The main concern I have so far is changing something in currently opened Xcode project.

**Comment by krzysztofzablocki** [comment]
Xcode should recognise it, it does when appcode changes the project

**Comment by tomlokhorst** [comment]
I assume you're talking about my project [XcodeEdit](https://github.com/tomlokhorst/XcodeEdit). Unfortunately it currently doesn't support _editing_ of xcodeproj files.

You can use another tool to edit the project.pbxproj file, it is an old-style plist file. So even a tool like `plutil` should work. XcodeEdit can then be used to reserialize the file to the format Xcode uses, to prevent a giant git diff. ([Example](https://github.com/tomlokhorst/pbxproj-serialize))

Alternatively, you can wait for editing support in XcodeEdit. It is a feature I need myself. I'm currently figuring what specifically I want to build. Generic editing of the complete xcodeproj file structure is a lot of work. But for my own needs, I also only need to add a file. So I'm considering just adding a highly specific method `addFile`, instead of completely implementing generic editing. This single method might also be sufficient for your needs?

**Comment by Cellane** [comment]
Alternatively, there's already the [xcproj](https://github.com/xcodeswift/xcproj) project, a Swift library that already supports reading, updating and writing Xcode project files. It also seems that it's been somewhat battle-tested in other projects, maybe Sourcery could take advantage of that?

**Comment by 1078966324** [comment]
你好 ，我是中国人。

**Comment by ilyapuchka** [comment]
@Cellane I was also looking into xcporj, it could be an option to migrate to it.
