### ISSUE TITLE
Danger doesn't have access to the PR from circle

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#463]
In #450 we missed the `CHANGELOG` changes, that usually caught by Danger, but the CI was green. After checking the logs I found:
```
All green. Nice work.

Danger does not have write access to the PR to set a PR status.
```

So probably something has changed, so Danger lost access to the PRs.

**Comment by krzysztofzablocki** [comment]
something else had to happen on that PR, that message is expected since we didn't add bot as the user of the repo per http://danger.systems/guides/faq.html#danger-is-not-posting-to-github-prs-but-everything-looks-fine

I refreshed the api token anyway, you can see that danger commented on #461 

Lets keep an eye on it for next pr in case its still funky
