### ISSUE TITLE
sourcery:inline:auto does not regenerate if deleted

### ISSUE THREAD

**Issue by ZevEisenberg** [krzysztofzablocki/Sourcery#467]
See [video](https://cl.ly/oZPK) and corresponding [sample project](https://cl.ly/oYxX).

Steps to reproduce:

1. Open the attached sample project in Xcode.
1. Build the project. Observe that memberwise `init`s are generated for the `Post` and `Person` types.
1. Delete the memberwise `init`s from both types. Maybe you wouldn't normally do this, but I did it a lot while getting my Sourcery template up and running.
1. Build the project again.

Expected: the memberwise `init`s are generated again.

Actual: the memberwise `init`s are not generated again. You may have to close and reopen the files to make sure, because Xcode 9.2 is sometimes reluctant to reload files that change on disk.

Workaround: `rm -r ~/Library/Caches/Sourcery` and then rebuild, and the code gen happens as expected.

Not sure if bug or expected behavior.

**Comment by ilyapuchka** [comment]
@ZevEisenberg thanks for amazing report! And nice to see swift templates being used =)

Looking at the code it seems like this behaviour is expected as we are using original content of the file when checking sources cache. This content is read before inline code is inserted. So after you delete it if there are no changes we will not rerun generation again.
Otherwise cache will always mismatch in case we insert any generated code in source file.
We maybe can update the cache after generation pass if file content changed. What do you think @krzysztofzablocki ?

I would suggest using `--disableCache` option as a workaround, especially during development process.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka I think that cache shouldn't play part in deciding whether we should write the code again, we ignore the code between inline markers for parsing (as we should) but the code should always be written as it might have changed due to template or other files changing

**Comment by Liquidsoul** [comment]
After digging into it a bit, I think the issue is more of a Cache bug than something we should change in the current process.
When Sourcery cannot find the `inline:auto` block, it'll try to find the body of the `Type` to insert it. But when run from the cache, it cannot get the body location.
It seems that the `__parserData` information on the `Type` here is not restored correctly when read from the Cache. It is used by `__underlyingSource` which is needed to find the [body position](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/FileParser.swift#L33-L35).

If you break on [Sourcery.swift:381](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Sourcery.swift#L381) when running Sourcery on Zev's sample project for the first time (no cache), you'll have this in lldb:
```lldb
(lldb) po parsingResult.types.types.map { $0.name }
▿ 5 elements
  - 0 : "AppDelegate"
  - 1 : "Entity"
  - 2 : "Person"
  - 3 : "Post"
  - 4 : "ViewController"

(lldb) po parsingResult.types.types[2].name
"Person"

(lldb) po parsingResult.types.types[2].__underlyingSource
▿ 10 elements
  ▿ 0 : 2 elements
    - key : "key.bodylength"
    - value : 121
  ▿ 1 : 2 elements
    - key : "key.nameoffset"
    - value : 167
  ▿ 2 : 2 elements
    - key : "key.accessibility"
    - value : "source.lang.swift.accessibility.internal"
  ▿ 3 : 2 elements
    - key : "key.length"
    - value : 137
  ▿ 4 : 2 elements
    - key : "key.substructure"
    ▿ value : 3 elements
      ▿ 0 : 8 elements
        ▿ 0 : 2 elements
          - key : "key.nameoffset"
          - value : 184
        ▿ 1 : 2 elements
          - key : "key.accessibility"
          - value : "source.lang.swift.accessibility.internal"
        ▿ 2 : 2 elements
          - key : "key.length"
          - value : 14
        ▿ 3 : 2 elements
          - key : "key.typename"
          - value : "String"
        ▿ 4 : 2 elements
          - key : "key.name"
          - value : "id"
        ▿ 5 : 2 elements
          - key : "key.kind"
          - value : "source.lang.swift.decl.var.instance"
        ▿ 6 : 2 elements
          - key : "key.namelength"
          - value : 2
        ▿ 7 : 2 elements
          - key : "key.offset"
          - value : 180
      ▿ 1 : 8 elements
        ▿ 0 : 2 elements
          - key : "key.nameoffset"
          - value : 203
        ▿ 1 : 2 elements
          - key : "key.accessibility"
          - value : "source.lang.swift.accessibility.internal"
        ▿ 2 : 2 elements
          - key : "key.length"
          - value : 16
        ▿ 3 : 2 elements
          - key : "key.typename"
          - value : "String"
        ▿ 4 : 2 elements
          - key : "key.name"
          - value : "name"
        ▿ 5 : 2 elements
          - key : "key.kind"
          - value : "source.lang.swift.decl.var.instance"
        ▿ 6 : 2 elements
          - key : "key.namelength"
          - value : 4
        ▿ 7 : 2 elements
          - key : "key.offset"
          - value : 199
      ▿ 2 : 8 elements
        ▿ 0 : 2 elements
          - key : "key.nameoffset"
          - value : 224
        ▿ 1 : 2 elements
          - key : "key.accessibility"
          - value : "source.lang.swift.accessibility.internal"
        ▿ 2 : 2 elements
          - key : "key.length"
          - value : 18
        ▿ 3 : 2 elements
          - key : "key.typename"
          - value : "Date"
        ▿ 4 : 2 elements
          - key : "key.name"
          - value : "birthday"
        ▿ 5 : 2 elements
          - key : "key.kind"
          - value : "source.lang.swift.decl.var.instance"
        ▿ 6 : 2 elements
          - key : "key.namelength"
          - value : 8
        ▿ 7 : 2 elements
          - key : "key.offset"
          - value : 220
  ▿ 5 : 2 elements
    - key : "key.name"
    - value : "Person"
  ▿ 6 : 2 elements
    - key : "key.kind"
    - value : "source.lang.swift.decl.struct"
  ▿ 7 : 2 elements
    - key : "key.namelength"
    - value : 6
  ▿ 8 : 2 elements
    - key : "key.offset"
    - value : 160
  ▿ 9 : 2 elements
    - key : "key.bodyoffset"
    - value : 175
```
And if you just run again without any change, here is what you'll have:
```lldb
(lldb) po parsingResult.types.types.map { $0.name }
▿ 5 elements
  - 0 : "AppDelegate"
  - 1 : "Entity"
  - 2 : "Person"
  - 3 : "Post"
  - 4 : "ViewController"

(lldb) po parsingResult.types.types[2].name
"Person"

(lldb) po parsingResult.types.types[2].__underlyingSource
0 elements
```

I'll try to find some time to dig into this issue more in the coming days.

**Comment by Liquidsoul** [comment]
I've looked into it and the issue is located in the [decoding](https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Type.swift#L306) of the `__parserData` in `Type`.

#### The problem

Initially, we assign a `[String: SourceKitRepresentable]` value with `SourceKitRepresentable` being Swift [`Array`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift#L21)s, [`Dictionary`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift#L22)s, [`String`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift#L23)s, [`Int64`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift#L24)s or [`Bool`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift#L25)s.

When we cache this information, we use `NSCoding` to [encode this value](https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Type.swift#L332).

Behind the scenes, this will convert the above types to their `NS` counterparts (`NSDictionary`, `NSArray`, `NSString`, `NSNumber`) that we will then decode when we [read from the cache](https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Type.swift#L306).

At this point, when we want to use this information (in our case here for `inline:auto`), the stored data is not what we expect it to be. [`__underlyingSource`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/FileParser.swift#L17-L19) will not be able to convert the data with a simple cast to `[String: SourceKitRepresentable]` because the underlying types in the data have changed to the `NS` ones.

#### The possible solutions 

##### Convert the data if necessary

I see this more as a workaround than a real fix to the problem, but this is the quickest way to have a working solution even if it's temporary.
This is what I've implemented in the branch [issue-467](https://github.com/krzysztofzablocki/Sourcery/tree/issue-467) in c811130832ede7b93514689eb3efa8f3540b934d.
The idea is to change the implementation of `__underlyingSource` which will check if `__parserData` holds an `NSDictionary` and convert it to a `[String: SourceKitRepresentable]`.

The downside I see here:
- the code is more complex and is tightly bound to the `SourceKittenFramework`. If they add a `SourceKitRepresentable` type, we'll need to update this code.
- I did not do some profiling, but we may see a reduction of the performance of Sourcery when it uses the cache mechanism (which means most of the use cases)

##### Use `Codable` to store `__parserData`

I tried to implement this but this one is tricky because of the architecture of `Sourcery` and `SourceryRuntime`.

If you try to use `Codable` here, the first issue is the type of `__parserData` which is `Any?`.
`Decodable` requires that you provide a type implementing the `Decodable` protocol, so we need to change this to make this work. We could add some type along the `Parsable` to encode the data and change the protocol accordingly.
But the object defining `__parserData` is `Type` in our case, which is defined in `SourceryRuntime`, and the `Parsable` protocol is defined in `Sourcery`. Doing this would require a dependency of `SourceryRuntime` on `Sourcery` which is not possible.
This means that we need to change the way we store the `__parserData` in `SourceryRuntime` which will require quite some thinking and changes to achieve.

My first idea would be to explicitly expose the information stored in `__parserData` using some elements we would define in `SourceryRuntime`.

#### Conclusion

I think we should integrate the workaround and discuss how we could fix the encode/decode issue.

What do you think?

**Comment by krzysztofzablocki** [comment]
@Liquidsoul @ilyapuchka the problem is that we are using `__underlyingData` inside Type extension, I vaguely remember that wasn't my intention for this (which is why its double underscored and private to FileParser).

Wouldn't all of this be fixed if we removed that method that relies on it, and instead just injected the body range as a proper argument? __underlyingData doesn't need to be cached then

**Comment by Liquidsoul** [comment]
@krzysztofzablocki Yes, that was my idea too, moving the information we use from `__parserData` to `Type` itself.
> My first idea would be to explicitly expose the information stored in `__parserData` using some elements we would define in `SourceryRuntime`.

In fact, It seems that `Type` is the only `Parsable` item where we encode `__parserData`. All other objects skip it.
From the history, it seems it was done for swift templates caching. We'll need to check for regressions there if we stop encoding it.

I'll work on moving the `__underlyingSource` information we use for `inline:auto` to `Type` which should fix the issue we have here. We'll then see if we can remove the caching of `Type.__parserData`.

**Comment by krzysztofzablocki** [comment]
@Liquidsoul but that property isn't used in any sources in the project other than the `bodyBytesRange` Type extension, don't move it, mark it as fileprivate and only use it in `FileParser`, the only change we need is to inject `bodyBytesRange` value to the `Type` rather than relying on `__underlyingSource`

Unless I'm misreading something this should be all thats needed, thoughts @ilyapuchka ?

**Comment by ilyapuchka** [comment]
It is used in two places as I can see, FileParser.swift:34 and FileParser.swift:249 to extract ranges for declaration body and key. If we get these ranges at parsing time and just store them in Type, we would not need to store the whole source (we can have a method that calculates all the ranges we might be interested in from Substring enum). I don't see __parsedData being used anywhere at all by itself except being a base for __underlyingSource. Should also be good for cache size, though I never benchmarked it. And I don't think it's related to swift templates caching, it's not used for it.
At the same time I don't see problem adding some decoding logic, I don't think SourceKitten will ever need to add any new types conforming to SourceKitRepresentable.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka the second use-case is the proper one, as that property is used to simplify Parsing, it should only be used for parsing, never ever should we use it for anything in any of our Types.

@Liquidsoul can you just replace the `bodyBytesRange` by injecting the value into the Type (at the end of parsing), and mark the parserData not codable ?

**Comment by Liquidsoul** [comment]
@krzysztofzablocki That's what I am working on. I'm just having some issues with SwiftTemplates tests. Context decoding seems to fail with the introduced `BytesRange` used in `Type.bodyBytesRange`.
