### ISSUE TITLE
Associated Types Parsing => Type Erasure

### ISSUE THREAD

**Issue by PaoloLongato** [krzysztofzablocki/Sourcery#502]
I am trying to parse a Protocol with associated types; from these types I need to generate classes (ideally bearing the name of the associated type) and method signatures (generic parameters equivalent to each associated type in the protocol).  From parsing protocols and printing out the whole "type" I don't think the information I need is collected.  Any plan to support?  Any pointer on how to add it myself if not?

**Comment by ilyapuchka** [comment]
For type erasure take a look at [this template](https://github.com/AliSoftware/SourceryTemplates/blob/master/Templates/TypeErase.stencil) by @AliSoftware 

We are not providing associated types information at this moment and it seems to be low priority for me. Usually associated types are inferred from other declarations, I barely had to declare them explicitly. Can you describe your use case with code snippets?

SourceKitten does not return associated types information so it should be parsed manually, probably similarly to how we parse typealiases. There also can be cases when some declaration uses associated type instead of typealias. In this case we should "infer" this type, similar to how we do that for typealiases in Composer, but it might be complicated, as typealias can be not declared and type can be inferred from some other declaration.
We can also file an issue in SourceKitten for this missing data and probably bug for Swift, but I don't think it will be addressed any time soon.

**Comment by PaoloLongato** [comment]
Thanks! Interesting, the template you linked to uses annotations to extract associated types. It could be a decent compromise, actually (I was not aware of annotations).  Essentially what I need to do is exactly what the template does.  Example.  Takes something like this:

```
// sourcery: TypeErase = MyAssociatedTypeA
protocol MyProtocol: TypeErased {

    associatedtype MyAssociatedTypeA
    //associatedtype MyAssociatedTypeB

    var foo: MyAssociatedTypeA? { get set }
    func toFoo(bar: MyAssociatedTypeA) -> MyAssociatedTypeA
}
```

And turn it in a series of 3 classes similar to this:

```
private class _AnyMyProtocolBase<MyAssociatedTypeA>: MyProtocol {
    init() {
                ....
    }

    func toFoo(bar: MyAssociatedTypeA) -> MyAssociatedTypeA {
        ....
    }

    var foo: MyAssociatedTypeA? {
        get { ... }
        set { ... }
    }
}
```

Except that in the real world I would need multiple associated types.

**Comment by ilyapuchka** [comment]
you can use the same annotation with different values, in this case values will be grouped in array.

**Comment by PaoloLongato** [comment]
Something like this is acceptable I think:

```
protocol TypeErased {}

// sourcery: AssociatedTypes = MyAssociatedTypeA, AssociatedTypes = MyAssociatedTypeB
protocol MyProtocol: TypeErased {

    associatedtype MyAssociatedTypeA
    associatedtype MyAssociatedTypeB

    var foo: MyAssociatedTypeA? { get set }
    func toFoo(bar: MyAssociatedTypeA) -> MyAssociatedTypeB
}
```

Then you can transverse in the stencils file:

```
{% for ann in type.annotations.AssociatedTypes %}
{{ ann }}
{% endfor %}
```

Maybe a bit verbose but works relatively cleanly.  Thanks a lot @ilyapuchka.
