### ISSUE TITLE
Working with Generics

### ISSUE THREAD

**Issue by AndriiDoroshko** [krzysztofzablocki/Sourcery#523]
What do i have?

`let start: CommandWith<Progress>`

Progress is ContentControlsViewController.Props.Progress

What do i want to get?

`public init(start: CommandWith<ContentControlsViewController.Props.Progress>) {}`

What i do have!

`public init(start: CommandWith<Progress>) {}`

Question:

How to get `type.name` instead of default `typeName` inside generic?

**Comment by ilyapuchka** [comment]
what are you using in template that outputs `CommandWith<Progress>`?

**Comment by ilyapuchka** [comment]
As a workaround you can use full type name in the property definition, if you can change code. Or you can deconstruct the type parameter and access it's `type.globalName` property to build full type name.

**Comment by AndriiDoroshko** [comment]
@ilyapuchka 
Simple:
`{{ variable.typeName }}`
But if i use:
`{{ variable.type.name }}` , it doesn't work at all...

How can i get type in generic type, and than, i wanna do checks like:
 `    {% if variable.type.**generic**.type.name != nil %}
           {{ case.associatedValues.first.type.name }}
       {% else %}
           {{ case.associatedValues.first.typeName }}` 
???
But `.**generic**` doesn't exist in sourcery and i couldn't find something similar

**Comment by AndriiDoroshko** [comment]
@ilyapuchka Could you give an example, please? 
Thanks)

**Comment by ilyapuchka** [comment]
`{% if variable.typeName.generic.typeParameter.type.actualTypeName %}` should give you global name of generic parameter, so it should be `ContentControlsViewController.Props.Progress`. But we should provide a better way for that, probably in this case `variable.typeName.actualTypeName` instead of `CommandWith<Progress>` should contain fully qualified type, so that it can be used in any context.

@krzysztofzablocki we should probably better document use of `typeName.actualTypeName` as this is usually one that should be used to produce type that can be used in any context, not only inside containing type.

**Comment by AndriiDoroshko** [comment]
@ilyapuchka Sorry, but `{{ variable.typeName.generic.typeParameter.type.actualTypeName }}` doesn't work(
`sourcery 0.10.1`

**Comment by ilyapuchka** [comment]
Yes, because there was no release yet since we implemented generic support, you need to get latest master version.

**Comment by AndriiDoroshko** [comment]
We use brew on the project, so i have to install it through the brew. 
When could release be expected in a brew?

**Comment by ilyapuchka** [comment]
Don't know, I think we can make release after pr with my fix is merged, there are a lot of things already. If not 1.0 then 0.11

**Comment by RomanTysiachnik** [comment]
@ilyapuchka looking forward for the next release ;)
