### ISSUE TITLE
Sourcery is not affected by `#if os(foo)`

### ISSUE THREAD

**Issue by mxcl** [krzysztofzablocki/Sourcery#530]
While making it compile on Linux I have noticed that `#if os(macOS)` blocks are ingested on Linux leading to generation of classes that don’t exist when compiled.

For example, I put `#if os(macOS)` inside everything in `Method.swift` (since I see no other way to conditionalize use for Sourcery) but the type is still generated into eg.`Description.generated.stencil`.

Suggestions? Work arounds? Fixes I can do to Sourcery itself? Thanks.

**Comment by ilyapuchka** [comment]
@mxcl yes, that's the issue we were discussing in #500. It seems that SourceKitten does not care about these conditions. So we need to do our own preprocessing before feeding files content to it, either by parsing these conditions or using some custom annotations to do the same.

**Comment by mxcl** [comment]
Thanks, sorry I missed that ticket. I did a search, so my bad search-fu. Probably I can work around this some other way for now.

**Comment by ilyapuchka** [comment]
I guess the easiest way for now is to annotate types, properties or methods which should be available conditionally, with some annotation and then check it in the template. I.e. if type should be only available on Linux it can be annotated with `// sourcery: platform=linux` and then you can check the value of this annotation in template. The problem is how to check for the platform in the template? Maybe we can add some environment properties to context, like platform and swift version, to start with.
