### ISSUE TITLE
Inline generation ignoring if

### ISSUE THREAD

**Issue by buscarini** [krzysztofzablocki/Sourcery#542]
I'm using this gist: https://gist.github.com/Liquidsoul/efa4f65af055acfde64afed6cda0007d

It should only work for types which are annotated with "AutoInit", but if I modify a file containing a struct this init gets inserted, even if the type isn't annotated. Am I the only one seeing this?

**Comment by buscarini** [comment]
Forgot to say that I'm using version 0.10.1

**Comment by ilyapuchka** [comment]
are you using watch mode?

**Comment by ilyapuchka** [comment]
This will not work like you would expect because when you remove annotation template will no more generate inline annotation for this type, so it will not be removed once it was inserted. You should rewrite template and put condition after annotation. This way annotation will be still inlined, but code between its start and end will be removed

```jinja
{% for type in types.structs %}
// sourcery:inline:auto:{{ type.name }}.AutoInit
{% if type|annotated:"AutoInit" %}
...
{% endif %}
// sourcery:end
{% endfor %}
```
