### ISSUE TITLE
Generate Quick and Nimble Spec from any Type

### ISSUE THREAD

**Issue by doozMen** [krzysztofzablocki/Sourcery#559]
I have a proposal to generate a template for starting quick and nimble tests from any type. I would like to add it. I do not you know very well how to use macro's and calls. Maybe this could be improved?

**Comment by ilyapuchka** [comment]
To be honest, I'm not sure about such use case for Sourcery and if we should include include such template. It seems like it's more suitable to implement this functionality as Xcode extension rather than using Sourcery for that. It does not seem like you really need to know about all the types, you only need to scan one file so just using SourceKitten in extension and a bit of json parsing should be enough. And what this template generates is a template that is changed later manually. It can be a valid use case for Sourcery, I think, if generated code would be complete with no need to change further and then just copy pasted. But in your case it's not and you just end up with unneeded traces of Sourcery in the code base that are not useful any more as generated code is not kept in sync with the rest of the code base and they can be just misleading over time.
@krzysztofzablocki what do you think?

**Comment by krzysztofzablocki** [comment]
agreed, it would make more sense for code extension, maybe we'll get more powerful plugins in next Xcode and we can revisit leveraging Sourcery for stuff like this

**Comment by doozMen** [comment]
I tried to use the inline capability of Sourcery to at least generate the setup of the spec in sync with the code. But if I do dat I can only add code to the file of the type that implements the `AutoSpecable` protocol. 
Would it be an idea to make the inline code generation work outside of the file of the type that implemts it like:

```swift
class BusServiceSpec: QuickSpec {

override spec() {
   describe("BusService") {
         // sourcery:inline:BusService.AutoSpecable
          // sourcery:end
   }
}
```

I do agree that fully automated is the way Sourcery should work. But maybe this is an example where only part of the code should be fully automated.

@ilyapuchka @krzysztofzablocki I guess you have a valid point. However in my opinion of you aim for full automation right from the start sometimes this is hard to achieve. I added this as a first step because of 2 reasons:

1. writing specs is needed and difficult for new people when they do not know where to start
2. Working with mocks is time consuming and spec have a lot of repetative work.

So my questing is could the inline capabilities be extended?

**Comment by ilyapuchka** [comment]
I believe inlining should work as long as files with annotations are scanned, so just provide your specs as sources to scan.
For mocks there is already a template, so this is covered. Bootstrapping could be useful indeed, but can't you use an Xcode templates and snippets for that with placeholders for developer to fill? I think should solve consistency issue.
