### ISSUE TITLE
Using our own fork of Stencil

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#567]
If we want to evolve Stencil templates to make using them with Sourcery (and SwiftGen) a less frustrating experience I suggest to switch to our own fork of Stencil. There are a lot of pull request with, in my opinion, valuable improvements, which are not moving anywhere already for few months, including white spaces control and various other cool features.

As we are using StencilSwiftKit it should be probably done on their side first. Or we can just include all its additional nodes and filters in this fork and drop StencilSwiftKit.

@krzysztofzablocki @AliSoftware what do you think?

**Comment by krzysztofzablocki** [comment]
I agree, kyle seems too busy and we shouldn't be blocked by that, Sourcery and SwiftGen are both used by much wider audience than Stencil itself afaik

**Comment by AliSoftware** [comment]
I agree that there are a lot of valuable improvements for Stencil that are pending. But I'm not sure having a fork is the right solution, because it could also diverge quite quickly (and users would then have to refer to different docs depending on if they are writing Stencil templates for the main Stencil or for our fork, because some tags will exist in one place but not the other…).

I think it would be better if @kylef would agree to give us Push access to Stencil so we can help him maintain it ?

**Comment by AliSoftware** [comment]
_btw I'm not sure if both of you have push access to StencilSwiftKit, if that's not the case don't hesitate to ask, I'll gladly give it to you._

**Comment by ilyapuchka** [comment]
I have push access to Stencil, but Sourcery and SwiftGen specifics require Stencil to be more dynamic, because final user has no control of context, than it may be needed for web frameworks where context is fully under control of user, so I think fork would be better.

**Comment by AliSoftware** [comment]
Ok seems like @yonaskolb would be interested in a fork too, for SwagGen and Genesis… so let's do this.

I'm gonna try and make a release of StencilSwiftKit tomorrow evening, then we could start forking and even make the fork absorb StencilSwiftKit to merge the two together.

**Comment by ilyapuchka** [comment]
I've tried to update references to Stencil with new location, but it fails for SPM, I guess it is blocked by https://github.com/SwiftGen/StencilSwiftKit/pull/88
