### ISSUE TITLE
Only generate/write file from template if it does NOT exist yet?

### ISSUE THREAD

**Issue by maximkhatskevich** [krzysztofzablocki/Sourcery#620]
Is there a way to make Sourcery generate/write to certain file path if it does not exist yet ONLY?

**Comment by maximkhatskevich** [comment]
Okay, got it. Thanks @ilyapuchka

**Comment by Pwyll28** [comment]
Does anyone has succeed doing this ? 
We're using TCA and i want to generate a full module with separated files.
Module+View
Module+Reducer
Module+Generated.
But i only want Module+Generated to be overwritten each time we execute sourcery. The other files need to be created only it they don't exists.
Maybe there's a `// sourcery:no-override:file:{{ scope.localName }}/{{ scope.localName }}+View.swift` parameter i'm not aware of ?

**Comment by Nikoloutsos** [comment]
@Pwyll28  
I have not implemented something like this but here is my idea.
Assuming that your code is under git version control.

You can run sourcery and after it you can discard modified files that has `.generated` substring in their names. Hence only new files will be left.

**Comment by krzysztofzablocki** [comment]
Sounds to me like you want to run Sourcery in bootstrap/generator mode for those files, I use that as a separate workflow where you can kick off a template from some Source data, rather than CLI integration. 

Also, this is the modus operandi for Sourcery Pro Xcode Extension albeit that can't generate new files due to Xcode plugin system limitations.

If you wanted to contribute something like this @Pwyll28 I'd be open to merging it
