### ISSUE TITLE
--args does not like the ":" character

### ISSUE THREAD

**Issue by daviskoh** [krzysztofzablocki/Sourcery#623]
Version: 0.13.1

Using Cocoapods for installation

Template

```
"{{ argument.url }}"
```

Running

```
$PODS_ROOT/Sourcery/bin/sourcery --sources . --templates ./Sourcery/Templates --args url="https://www.url.com" --output ./output-dir
```

will produce

```
""
```

Running (notice the lack of `:`)

```
$PODS_ROOT/Sourcery/bin/sourcery --sources . --templates ./Sourcery/Templates --args url="https//www.url.com" --output ./output-dir
```

will produce

```
"https//www.url.com"
```

This does not seem to be a Stencil issue as I tried cloning https://github.com/stencilproject/Stencil and running those tests supplying `"https://www.url.com"` into templates and it rendered fine.

I am not entirely sure what is going on. I have spent a bit of time looking through the source code, but unable to devote any further time looking into it. I suspect the cause is some sort of parsing / validation where the character `:` is either removed or used as a marking point in the string for parsing causing this unexpected behavior.

Is this the intended behavior? I am perfectly ok working around it for now, it could be good to document it somewhere.

**Comment by ilyapuchka** [comment]
@daviskoh I think the problem is not in code but in how arguments with quotes are decoded by Foundation - if you use `"` they will be removed from string, which will lead to value `arg= https://www.url.com` which will be parsed by extracting everything before `:` to argument name, so it will be `url=https` and its value will be `//www.url.com`. But if you escape it with `\"` quotes will stay and argument will be parsed correctly.

**Comment by daviskoh** [comment]
@ilyapuchka so Sourcery ***is*** using `:` as a marker point to parse args?

**Comment by ilyapuchka** [comment]
It uses the same function as for annotations where `:` is a namespace separator. But it ignores colons in strings surrounded by `"`

Ilya Puchka

Отправлено с iPhone
