### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by jakubvano** [krzysztofzablocki/Sourcery#629]
First off, thanks for this awesome tool 👍 
I've started to enjoy working with Sourcery, and begun to explore some possibilities of how it could be used to enhance other libraries. I've come upon two features that would IMO help push the framework in this direction:

###  Inline Xcode error messages
Basically enable templates (swift templates at least) to raise errors which would be displayed as inline errors (warnings ?) in Xcode, in similar fashion as is done for example by SwiftLint. This would AFAICS require
 - Some mechanism of propagating these errors from templates to main process (custom throwable error, or method for "logging" this information ?)
 - Source code location (file/line) information for scanned identifiers. I'm not sure how/if this would be feasible.

### Accessing external code from templates
Writing more complex logic directly in (Swift) templates is not ideal - if nothing else, than language options are quite limited due to the fact that the template code runs inside `TemplateContext.generate` method.
I would love to see an option, which would enable me to declare which source files I want to be compiled along with the template, or possibly even frameworks I want to be linked with the template executable.

Is this something that would be a viable addition to the library? If so, do you have any ideas / suggestions how might one go about implementing these?

**Comment by ilyapuchka** [comment]
Errors are also ready propagated into the main process, but depending on what templates (stencil, swift or ejs) you use they may be more or less helpful. For Stencil template there is a long standing pr to improve this https://github.com/stencilproject/Stencil/pull/167, but as you can see the project is pretty stale for quite some time already.
EJS probably are the best here because template engine takes care already of printing errors, but I still can imagine them being not very accurate, especially if they happen at runtime.
In swift templates propagating errors seems to be more complicated as they run as a separate process and it's harder to get concrete information about line of error, so it should be implemented inside swift template "engine", similar to EJS.

For source code location we store this information in a property, which can be actually accessed in a template as it is `public`, but it's not documented as it is used privately for some implementation. Problem with that might be extensions as they are merged together into type they extend, but we can still keep origins of their declarations (methods and properties). I don't see though how much useful this information can be for regular code generation tasks, unless you are trying to use Sourcery as a tool to facilitate some other task, like docs generation, which is out of scope of Sourcery.

Executing arbitrary code in swift templates can be achieved with #509 , but in my practice I never needed it, creating helper methods was enough.

**Comment by ilyapuchka** [comment]
Including external code is now possible with `include` tag supporting swift files. Regarding errors from swift template don't think we can improve them a lot right now without rethinking how they are compiled/executed.
