### ISSUE TITLE
Variable.type.name equality check always succeeds if it is nil

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#644]
This is a weird one.

## Minimal Example

Given `test.swift`,

```swift
protocol Proto {}
struct Foo: Proto {
    var bar: Int = 1
    var baz: String = "2"
}
```

and `template.stencil`

```
/*
{% for t in types.based.Proto %}
in {{t.name}}:
{% for p in t.storedVariables %}
{% if p.type.name == Int %}
is Int: {{p}}
{% endif %}
{% endfor %}
{% endfor %}
*/
```

### Actual Output 

Running `sourcery --sources test.swift --templates template.stencil` produces this output:

```swift
// Generated using Sourcery 0.13.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

/*
in Foo:
is Int: Variable: name = bar, typeName = Int, isComputed = false, isStatic = false, readAccess = internal, writeAccess = internal, isMutable = true, defaultValue = Optional("1"), annotations = [:], attributes = [:], isFinal = false, definedInTypeName = Optional(Foo), actualDefinedInTypeName = Optional(Foo)
is Int: Variable: name = baz, typeName = String, isComputed = false, isStatic = false, readAccess = internal, writeAccess = internal, isMutable = true, defaultValue = Optional("\"2\""), annotations = [:], attributes = [:], isFinal = false, definedInTypeName = Optional(Foo), actualDefinedInTypeName = Optional(Foo)
*/
```

### Expected Output

The check is `{% if p.type.name == Int %}`. Since `name` is a String and there are no quotation marks around the phrase `Int`, I expected this to fail, so nothing would be generated besides `in Foo:`. But instead, it _always_ succeeds.

## Discussion

This, of course, is because I fell for `p.type`. Since the types of the properties are not owned by me, they are not known to Sourcery/Stencil. `p.type` is nil. Apparently, `{% if nil == Int %}` always succeeds. ~(I'd have expected to get an an error or at least `false`.)~
_Edit:_ Ah, of course -- `Int` is treated as a variable name, here. `{% if nil == "Int" %}` correctly evaluates to false.

If you check using `{% if p.typeName == Int %}`, the check simply fails. 

It _also_ fails for `{% if p.typeName == "Int" %}`, by the way, so I cannot figure our how to write a condition for the property type.

(Using Sourcery v0.13.1)

**Comment by DivineDominion** [comment]
Nevermind, `nil == nil` should succeed 👍

**Comment by ilyapuchka** [comment]
`variable.typeName` is of type `TypeName`, to get a string to compare it with another string you need to use it's `name` or `unwrappedTypeName` (which will also remove "?"/"!") property, so it will be `variable.typeName.name` or `variable.typeName.unwrappedTypeName` (usually you should always unwrap it)
In `{% if p.type.name == Int %}`you need to use quotes, as otherwise Stencil tries to resolve it as variable instead of string literal. This resolves to nil, as well as `type.name` because `type` is nil, as you are using built in types, which are not scanned by Sourcery.
So what you need it `{% if p.typeName.name == "Int" %}` or `{% if p.typeName.unwrappedTypeName == "Int" %}`.
