### ISSUE TITLE
Release date for Swift 4.2 ?

### ISSUE THREAD

**Issue by Gruppio** [krzysztofzablocki/Sourcery#680]
Hi, do you already have an idea about the release date for make it compatible with Swift 4.2 ? 
Thank you!

**Comment by petaren** [comment]
Not a contributor. I tried getting it to compile and run with XCode 10. It seems like most/all of Sourcerys' dependencies have been updated, but I'm not able to compile due to other issues.

**Comment by amichnia** [comment]
Same here, I had a lot of troubles with building in Xcode 10. From what I tried, these are some issues:
- StencilSwiftKit - array literals containing closed range literals (SwiftIdentifier.swift) is too complicated for new compiler
- libCommonCrypto - could be removed in general, CommonCrypto is now visible from swift without the need for custom module maps
- some dependencies fail with optimization turned on, -Onone seems to work for them, but not 100% sure. I don't recall particular one though, maybe xcproj
- SourceryRuntime - at least for me it failed due to group structure not matching folders structure

I still fail in CodeSign path though, will give it a better look, as I'm really looking forward to use it with XCode 10

**Comment by krzysztofzablocki** [comment]
I'm completely swamped with commercial work, and I imagine a lot of our core team is in similar situation right now, so we could use some help here.

First step is to update dependencies that aren't upto date like SourceKitten, Stencil and StencilSwiftKit because when I did last update their respective dependencies were messed up, those things are resolved now I think so that would be the first thing someone needs to do. 

That should resolve some issues and allow us to figure out next steps

**Comment by ilyapuchka** [comment]
0.15.0 with Xcode 10 and Swift 4.2 support is released
