### ISSUE TITLE
[Question] How do I make AutoMockable work for protocols that inherit from UIKit protocols

### ISSUE THREAD

**Issue by manan19** [krzysztofzablocki/Sourcery#725]
```
// sourcery: AutoMockable
protocol ViewControllerListener: UITableViewDataSource {
    func sectionType(for sectionIndex: Int) -> Section
}
```

I'm trying to generate the mock for `ViewControllerListener` and get the error `Type 'ViewControllerListenerMock' does not conform to protocol 'UITableViewDataSource'`.

Sourcery doesn't seem to generate mocks for `UITableViewDataSource` methods.

@ilyapuchka @krzysztofzablocki What's the best way to implement this within Sourcery?

**Comment by krzysztofzablocki** [comment]
Sourcery doesn't know what `UITableViewDataSource` is because its unknown type (it doesn't get declared in the sources that you give to Sourcery) so it has no information about its method.

If you want to support things like this the easiest would be to just add a file to your project that isnt in any target but re-defines that protocol (you probably can just copy from the Swift generated interface) that way the tool would understand what there is
