### ISSUE TITLE
Xcode 10.2 - Sourcery 0.16 - The folder “context.bin” doesn’t exist.

### ISSUE THREAD

**Issue by Bino90** [krzysztofzablocki/Sourcery#739]
Hi,

with Xcode 10.2, which appeared today, I have the following issue:

Error Domain=NSCocoaErrorDomain Code=4 "The folder “context.bin” doesn’t exist." UserInfo={NSFilePath=/var/folders/1t/9p5d9klj6f94rqqlqh4hpc2w0000gn/T/SwiftTemplate/0.16.0/context.bin, NSUserStringVariant=Folder, NSUnderlyingError=0x7ff9e677e250 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

any ideas?

**Comment by brannpark** [comment]
I have a similar issue with Xcode 10.2.

error: Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/brannpark/Library/Caches/Sourcery/Mock.swifttemplate/5Dp3a9vTHHHYxDu9t5KHfVXiVAsjOAEWk3HrPc2Gnbg%3D, NSFilePath=/var/folders/5b/qxxx85bn0qq9yr6zqdvxv66r0000gp/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7fb2118d6bf0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by Max-Mikharev** [comment]
I have the same problem
error: Error Domain=NSCocoaErrorDomain Code=4 "The folder “context.bin” doesn’t exist." UserInfo={NSFilePath=/var/folders/7v/qm_v7vbn7pq5kh40cmll989hzfyjbc/T/SwiftTemplate/0.16.0/context.bin, NSUserStringVariant=Folder, NSUnderlyingError=0x7f900cedcca0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by RalfK92** [comment]
Well i think its not related to XCode 10.2 but more to macOS Mojave 10.14.4 because i have the same problem as mentioned by @Bino90 (we are working on the same project) but i just installed the macOS Update and did not install the XCode update yet.

**Comment by spuliaiev** [comment]
Try to clean ~/Library/Caches/Sourcery folder, it helps me.

**Comment by Bino90** [comment]
Yeah perfect thanks, this fix my issue
