### ISSUE TITLE
AutoCodable for classes

### ISSUE THREAD

**Issue by JakubMazur** [krzysztofzablocki/Sourcery#753]
I followed guide https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Codable.md for using `AutoCodable` template and read the `.swifttemplate` file and found that it's not designed to work with classes but only with structs and enums:

```
<%_ for type in types.all
                where (type is Struct || type is Enum)
                && (type.implements["AutoDecodable"] != nil || type.implements["AutoEncodable"] != nil) { -%>
    <%_ let codingKeys = codingKeysFor(type) -%>
    <%_ if let codingKeysType = type.containedType["CodingKeys"] as? Enum, codingKeys.generated.count > 0 { -%>
// sourcery:inline:auto:<%= codingKeysType.name %>.AutoCodable
        <%_ for key in codingKeys.generated { -%>
        case <%= key %>
        <%_ } -%>
// sourcery:end
<%_ } -%>
```

There is any special reason for that why `CodingKeys` for classes cannot be generated or it's possible and I should extend the template?

**Comment by ilyapuchka** [comment]
Classes will need quite different handling because they will need to use `superDecoder` and `super.init` and also consider that keys for inherited properties are defined in the base class, as well as some more complex scenarios like one described [here](https://medium.com/tsengineering/swift-4-0-codable-decoding-subclasses-inherited-classes-heterogeneous-arrays-ee3e180eb556).
But at least basic support is still possible.

**Comment by JakubMazur** [comment]
Sure, I now have class support but like you said without subclassing. Will try to test subclassing options with templating.
