### ISSUE TITLE
Global typealias types are ignored, unless extended

### ISSUE THREAD

**Issue by radianttap** [krzysztofzablocki/Sourcery#765]
If I have a Swift code like this:

```
typealias UserResult = Result<User, AccountError>
```

this type `UserResult` does not appear in `types.all`. 
If I do something like this:

```
extension UserResult {
...
}
```

then sourcery will add it into `types.all` but `type.name` will be `Result<User, AccountError>` instead of `UserResult` what I expected.

I read through many issues mentioning `typealias` here, but it's not clear to me is this correct behavior or a bug?

**Comment by ilyapuchka** [comment]
I think it's expected for this extension to have `type.name` as it is because that's the actual type (typealiases are not considered as types neither by Swift nor by Sourcery). It's `typeName` would be the name of the type alias though.
IIRC we don't still support global typealiases, only those defined inside other types (and that's not even documented, I would guaranty its supported 100% correctly)

**Comment by radianttap** [comment]
Thanks for the answer, this is rather unfortunate for my case. 

> typealiases are not considered as types neither by Swift nor by Sourcery

Can you point me to some reading materials for this? I don't quite understand "not considered as type" since it's cetainly used as type around the code.

**Comment by radianttap** [comment]
I went a bit through Sourcery source code and I see where are typealises processed and _not_ added into `types` collection. But did not manage to patch them in, not as straight-forward as I hoped. I'll post a PR if I manage to do something reasonable.

**Comment by ilyapuchka** [comment]
I just mean that in Swift typealias is just a shortcut for a type, or a template of it in case it has generic parameters (that's btw probably another thing that we don't support), so you can't for instance have `typealias A = Foo` and `typealias B = Foo` and use them (i.e. extend) as separate types unlike `class/struct A: Foo {}` and `class/struct B: Foo`, it will be always just `Foo` under the hood. So treating it the same as any other `Type` in Sourcery might be not the right way, if that's what you mean, even if technically achievable. I.e. we could make a `case typealias` as a new kind of `Type` instead of having a separate `Typealias` type and treat inner typealiases as inner types, but then this type will likely need to copy all of the attributes of the actual type. And what's even more concerning is that most of the templates will need to consider typealiases explicitly because most of the time they don't need them, i.e. if you have a typealias of a type that implements AutoEquatable you don't want an extension with generated code for equality both for the original type and the typealias.
We can have them available in `class Types` as a separate collection though, there we could have both global (if we ever parse them) and inner typealiases

**Comment by radianttap** [comment]
Thanks for explanation, I understand the issue.

To explain a bit why I need typealiases: I use typealias to make Result<X, Y> more readable in function params + to allow easy boxing into NSObject subclasses to cooperate with Objective-C types. For example:
```
typealias UserResult = Result<User, AccountError>

final class UserResultBox: NSObject {
	let unbox: UserResult
	init(_ value: UserResult) {
		self.unbox = value
	}
}
extension UserResult {
	var boxed: UserResultBox { return UserResultBox(self) }
}
```
Thus the only need thing I would need the actual typelias type name is to generate this code automatically. Ideally, I would write:

```
typealias UserResult = Result<User, AccountError>
extension UserResult: AutoBoxable {}
```
or
```
//sourcery: AutoBoxable
typealias UserResult = Result<User, AccountError>
```

`extension` approach would work even with Sourcery as it is now, _if only_ it did not hide the typealias name.

**Comment by ilyapuchka** [comment]
I guess you could still achieve that by iterating through extensions as they are and searching for the typealias with `typeName` matching the type of the extension. Probably won't be an optimal solution but would work.

**Comment by radianttap** [comment]
What do you mean by this:

> searching for the typealias with `typeName` ...

I tried print out all the type info:

```
{% for type in types.implementing.AutoBoxable %}
//    {{type.typeName}}
{% endfor %}
```

and for the typealias OrderResult (same as UserResult in examples above), I get this:

```
Type: 
	module = nil,
	typealiases = [:],
	isExtension = true,
	kind = extension,
	accessLevel = internal,
	name = Result<Order, OrderError>,
	isGeneric = false,
	localName = Result<Order, OrderError>,
	variables = [],
	methods = [],
	subscripts = [],
	initializers = [],
	annotations = [:],
	staticVariables = [],
	staticMethods = [],
	classMethods = [],
	instanceVariables = [],
	instanceMethods = [],
	computedVariables = [],
	storedVariables = [],
	inheritedTypes = ["AutoBoxable"],
	containedTypes = [],
	parentName = nil,
	parentTypes = AnyIterator<Type>(_box: Swift._IteratorBox<Swift._ClosureBasedIterator<SourceryRuntime.Type>>),
	attributes = [:]
```

I checked `localName`, `unwrappedName` etc - original typealias is not to be found.
