### ISSUE TITLE
No Brews Available for Earlier Versions

### ISSUE THREAD

**Issue by mishkaechoes** [krzysztofzablocki/Sourcery#877]
We are not yet able to upgrade to XCode 12 but the forced upgrade recently no longer supports 10

Is it possible to make older brews available? Such as version `0.17.0`

**Comment by krzysztofzablocki** [comment]
They are always available since it's in git history, it's just a bit of a hassle https://remarkablemark.org/blog/2017/02/03/install-brew-package-version/

Alternatively you can also use Mint https://github.com/yonaskolb/Mint or simply binary distribution that Sourcery is always bundled with to grab whichever version you want
