### ISSUE TITLE
configuration: Linking inside the root group

### ISSUE THREAD

**Issue by nnnax** [krzysztofzablocki/Sourcery#906]
I've created a very basic Xcode project named "simple" 
I want to link my generated files directly inside the default group named "simple" so my configuration file is set as follow : 

<img width="853" alt="Capture d’écran 2021-02-24 à 23 20 04" src="https://user-images.githubusercontent.com/2895717/109073971-621d0200-76f7-11eb-8523-850b5ab9216c.png">

After each Sourcery generation, a new group named "simple" is created
I expect to have my files added to the default group :

<img width="323" alt="Capture d’écran 2021-02-24 à 23 21 52" src="https://user-images.githubusercontent.com/2895717/109074464-14ed6000-76f8-11eb-9ace-38c2f60fd2a8.png">

After investigation, the default group name is empty (should be set to "simple" in my opinion) but the default group path is set to "simple" 

So I've applied a temporary fix in Sourcery.swift :

<img width="891" alt="Capture d’écran 2021-02-24 à 23 33 31" src="https://user-images.githubusercontent.com/2895717/109074969-c8565480-76f8-11eb-85ad-1818032cb8f5.png">

It does the job for me but maybe it's not really a definitive solution

Kind Regards

**Comment by krzysztofzablocki** [comment]
@nnnax hey, what happens if you don't specify the group name in the config? I'm looking at docs and they say that it should add the files to your root group

**Comment by nnnax** [comment]
Hi @krzysztofzablocki,
If I don't specify the group, my file is added under the project node (so near my default group) exactly as we see in the second screenshot. I think it's the expected behavior because the root group is the project node.

And the code itself is correct, I mean by default the rootGroup is used :
        var fileGroup: PBXGroup = rootGroup

But, I think the real problem is that my rootGroup children are not correctly defined (maybe an issue in xcodeproj)
If I loop through my rootGroup children, the child representing my "default group" has a "name" property empty

<img width="307" alt="Capture d’écran 2021-02-25 à 09 18 08" src="https://user-images.githubusercontent.com/2895717/109124177-eb115900-774a-11eb-9cb1-b009272b2932.png">

**Comment by krzysztofzablocki** [comment]
Ok, thanks for detailed write up 🙇‍♂️

I'll fix it but likely in next release after 1.3 since 1.3 is already going to be massive

**Comment by nnnax** [comment]
@krzysztofzablocki  
Just to let you know, after an in-depth analysis, in fact the issue is exactly the same as the issue #904 

There is two different types of groups in Xcode since version 9

- Groups with folders (a folder exists on the disk, associated to the group)
- Groups without folders (a virtual folder for organizing files)

If we use "Groups with folders" (actually used in Sourcery)
The output path doesn't make sense, and the files should be generated physically inside the folder associated the group 

If we use "Groups without folders" 
The output path can be used as the target for generated files
The group is only a virtual place for the file inside Xcode

In both case, the code should check for existing groups to avoid duplicate groups
In both case, if a file is generated physically somewhere, and if we change the location, the existing one should be removed to avoid compilation issue

not so easy, but I'am still working on it as I really plan to use Sourcery for my project


Regards,
Benjamin

**Comment by krzysztofzablocki** [comment]
@nnnax for now you could just not use automatic linking feature, as to not be blocked from using the tool. Right now I'm wrapping up 1.3 release which massively improves parsing (upto 12x faster) and reduces memory usage and after that I want to start prototyping more powerful AST but I'll take a look at fixing this before I do that since it's much smaller feature than AST overhaul 😂

**Comment by nnnax** [comment]
@krzysztofzablocki
Great to know that the tool is going to be improved ! I'm using it right know, I'm learning Stencil also. I'm not blocked 👍

**Comment by rubensamsonyan** [comment]
Hi there,

I'm using the sourcery 1.6.1 version to generate some mocks in the project I'm working on now. Almost everything works great and I'm using the output path to physically locate the files and using target and group to automatically link the generated files. I'm using cocoapods with some development pods and the target I'm trying to link is one of these pods. The linking works perfectly, but on the first run, sourcery generates a second "Development Pods" folder and then keeps using that generated one ignoring the original one.

I see this issue was reported from version 1.3 and I wonder if it is in the plan to fix. I can try to help with this, as this will help me quite a lot with the project setup.

**Comment by rubensamsonyan** [comment]
I did a little bit of investigation and find out the issue. Opened a [PR](https://github.com/krzysztofzablocki/Sourcery/pull/1017)
